Finding boulders that were rated highly specifically by women



1.   API call to Mountain Project for boulders in a specific region

2.   For each boulder problem, pull out the user stars, ticks, and grade ratings. 

3.   Combine the above dataframes into one that includes all of the information for that boulder problem. 

4.   Once that has been completed, repeat for all boulder problems. 

5.   Use the combined dataframe for all boulder problems to find the user ID and name of all unique relevant users. 

6.   Pull the user data and make a user personal information database. 

7.   Combine the boulder problem database wtih the user information database. 

8.   Now all of the data is processed together, so I can start analyzing it. 

* How much information do I have on users? How many are missing data, etc
* How well am I guessing the gender of users?  I think the guesser is biased towards names of European descent.
* For each boulder problem, Display rating for overall, male, female, undetermined. 
* Also pull out dataframe of comments from women.
* Do I want to use AI to guess user gender from their comments attached to their ticks?

In [32]:
# Import packages
import climbing_functions
from bs4 import BeautifulSoup # https://beautiful-soup-4.readthedocs.io/en/latest/
import copy
from datetime import datetime
import gender_guesser.detector as gender
import io
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import pickle
import requests # https://requests.readthedocs.io/en/latest/
import time
import urllib.parse

In [33]:
# set variable values

HEADERS = {'User-Agent': 'Independent research project - contact: carlybond907@gmail.com'}

# Go to Mountain Project and navigate to climbing area of interest. Open the Find routes button and filter for all routes of interest. 
# In the original use case, filter for all boulder problems. 
URL = "https://www.mountainproject.com/route-finder?diffMaxaid=75260&diffMaxboulder=20450&diffMaxice=38500&diffMaxmixed=65050&diffMaxrock=2800&diffMinaid=70000&diffMinboulder=20000&diffMinice=30000&diffMinmixed=50000&diffMinrock=1800&is_sport_climb=1&is_top_rope=1&is_trad_climb=1&pitches=0&selectedIds=105744225&sort1=area&sort2=rating&stars=0&type=boulder&viewAll=1"
# "https://www.mountainproject.com/route-finder-export?diffMaxaid=75260&diffMaxboulder=21700&diffMaxice=38500&diffMaxmixed=65050&diffMaxrock=5500&diffMinaid=70000&diffMinboulder=20000&diffMinice=30000&diffMinmixed=50000&diffMinrock=1800&is_sport_climb=1&is_top_rope=1&is_trad_climb=1&pitches=0&selectedIds=105716862&sort1=area&sort2=rating&stars=0&type=boulder&viewAll=1"

AREA_NAME = "Flagstaff_V0_to_V4"

#"Big_Bend_Bouldering"

In [34]:
#Create subdirectory

os.makedirs("data", exist_ok=True)  # creates folder if it doesn't exist

In [35]:
csv_df = retrieve_overview_csv(URL)

# Save overview df
csv_df.to_csv(f"data/{datetime.now().strftime('%Y%m%d_%H%M%S')}_{AREA_NAME}_csv_df.csv", index=False)

ParserError: Error tokenizing data. C error: Expected 1 fields in line 6, saw 4

In [61]:
all_routes_stats_df = fill_area_df_with_stats(area_df = csv_df)

{'Death Flakes': 'https://www.mountainproject.com/route/stats/114444130/death-flakes', 'Rampage': 'https://www.mountainproject.com/route/stats/106135567/rampage', 'Press tight': 'https://www.mountainproject.com/route/stats/112359419/press-tight', 'The Grim Reacher': 'https://www.mountainproject.com/route/stats/106135578/the-grim-reacher', 'Circus Trick': 'https://www.mountainproject.com/route/stats/105717433/circus-trick', 'Circus Trick Right': 'https://www.mountainproject.com/route/stats/106127755/circus-trick-right', 'Chaos': 'https://www.mountainproject.com/route/stats/106013793/chaos', 'Hell Belly Stand': 'https://www.mountainproject.com/route/stats/107957139/hell-belly-stand', 'Grim Reacher Direct': 'https://www.mountainproject.com/route/stats/109990646/grim-reacher-direct', 'Phantom Fighter (Stand)': 'https://www.mountainproject.com/route/stats/109990741/phantom-fighter-stand', 'Hell Belly': 'https://www.mountainproject.com/route/stats/106379808/hell-belly', 'Phantom Fighter': 'https://www.mountainproject.com/route/stats/105804658/phantom-fighter', 'Back Alley': 'https://www.mountainproject.com/route/stats/112386213/back-alley', 'Back Alley Left': 'https://www.mountainproject.com/route/stats/112386225/back-alley-left', 'Center Start': 'https://www.mountainproject.com/route/stats/106115877/center-start', 'Slots of Fun': 'https://www.mountainproject.com/route/stats/106115881/slots-of-fun', 'Arete Left Side': 'https://www.mountainproject.com/route/stats/105804667/arete-left-side', 'Center Direct': 'https://www.mountainproject.com/route/stats/109054130/center-direct', 'Traverse Slots': 'https://www.mountainproject.com/route/stats/127391870/traverse-slots', 'Arete Right Side': 'https://www.mountainproject.com/route/stats/105804671/arete-right-side', 'Shorter Traverse': 'https://www.mountainproject.com/route/stats/123952264/shorter-traverse', 'Bum Steer': 'https://www.mountainproject.com/route/stats/117402846/bum-steer', 'Arete Left Side Sit Start': 'https://www.mountainproject.com/route/stats/107931799/arete-left-side-sit-start', 'Blue Light': 'https://www.mountainproject.com/route/stats/107932354/blue-light', 'Kick Start': 'https://www.mountainproject.com/route/stats/106115856/kick-start', 'Leftover Lover': 'https://www.mountainproject.com/route/stats/106115860/leftover-lover', 'The Crimp Challenge': 'https://www.mountainproject.com/route/stats/106115852/the-crimp-challenge', 'Lip Traverse': 'https://www.mountainproject.com/route/stats/106115864/lip-traverse', 'The Pregnancy Arete': 'https://www.mountainproject.com/route/stats/107931744/the-pregnancy-arete', "Mr. Trujillo's Big Day": 'https://www.mountainproject.com/route/stats/105916291/mr-trujillos-big-day', 'Kick Start Low': 'https://www.mountainproject.com/route/stats/107931731/kick-start-low', 'Silly Wabbit': 'https://www.mountainproject.com/route/stats/107492628/silly-wabbit', 'Dyno for Dollars': 'https://www.mountainproject.com/route/stats/106115871/dyno-for-dollars', 'Double Crimp': 'https://www.mountainproject.com/route/stats/107492624/double-crimp', '1000 LB Caboose': 'https://www.mountainproject.com/route/stats/107931740/1000-lb-caboose', 'Unknown': 'https://www.mountainproject.com/route/stats/112401650/unknown', "Sticky's Arete": 'https://www.mountainproject.com/route/stats/121899177/stickys-arete', 'Shot Hole Traverse': 'https://www.mountainproject.com/route/stats/106870906/shot-hole-traverse', 'Skinless Dyno': 'https://www.mountainproject.com/route/stats/121750392/skinless-dyno', 'schizzle': 'https://www.mountainproject.com/route/stats/106280485/schizzle', 'Satya': 'https://www.mountainproject.com/route/stats/106203495/satya', 'Space Needle': 'https://www.mountainproject.com/route/stats/117339587/space-needle', 'LSD Saint': 'https://www.mountainproject.com/route/stats/106203523/lsd-saint', 'Slopey': 'https://www.mountainproject.com/route/stats/107719879/slopey', 'Descent': 'https://www.mountainproject.com/route/stats/121743416/descent', 'Block Shock': 'https://www.mountainproject.com/route/stats/106960653/block-shock', 'Block Pock': 'https://www.mountainproject.com/route/stats/120316260/block-pock', 'Brown Power': 'https://www.mountainproject.com/route/stats/106347517/brown-power', 'Squashed Arete': 'https://www.mountainproject.com/route/stats/114096020/squashed-arete', 'Block Party': 'https://www.mountainproject.com/route/stats/106960646/block-party', 'Slappin the Block': 'https://www.mountainproject.com/route/stats/107492580/slappin-the-block', 'Whodunnit': 'https://www.mountainproject.com/route/stats/107492589/whodunnit', "Slappin' The Block Sit Start": 'https://www.mountainproject.com/route/stats/107931839/slappin-the-block-sit-start', 'Five Finger DIscount': 'https://www.mountainproject.com/route/stats/106845593/five-finger-discount', "Eric's": 'https://www.mountainproject.com/route/stats/107931852/erics', 'Short Stuff': 'https://www.mountainproject.com/route/stats/107931756/short-stuff', 'Mueve se!': 'https://www.mountainproject.com/route/stats/106156004/mueve-se', 'The Punisher': 'https://www.mountainproject.com/route/stats/107543785/the-punisher', 'La Derecha': 'https://www.mountainproject.com/route/stats/106148146/la-derecha', 'Blankety Stand': 'https://www.mountainproject.com/route/stats/107924308/blankety-stand', 'La Derecha SDS': 'https://www.mountainproject.com/route/stats/127324725/la-derecha-sds', 'Blankety Blank': 'https://www.mountainproject.com/route/stats/106148107/blankety-blank', 'Washing Machine': 'https://www.mountainproject.com/route/stats/107633000/washing-machine', 'Unnamed V3': 'https://www.mountainproject.com/route/stats/112911753/unnamed-v3', 'Washed Up': 'https://www.mountainproject.com/route/stats/106588054/washed-up', 'Washed Up Extension': 'https://www.mountainproject.com/route/stats/112807600/washed-up-extension', 'Hueco Finish': 'https://www.mountainproject.com/route/stats/107924296/hueco-finish', 'Upwardly Mobile (AKA Hueco Cranks)': 'https://www.mountainproject.com/route/stats/107624646/upwardly-mobile-aka-hueco-cranks', 'Hueco Traverse': 'https://www.mountainproject.com/route/stats/106115846/hueco-traverse', 'Wussula': 'https://www.mountainproject.com/route/stats/107936921/wussula', 'Standula': 'https://www.mountainproject.com/route/stats/107936911/standula', 'Scoopula': 'https://www.mountainproject.com/route/stats/106588048/scoopula', 'Pancake Mantle': 'https://www.mountainproject.com/route/stats/107400070/pancake-mantle', 'Sand Traverse': 'https://www.mountainproject.com/route/stats/106115893/sand-traverse', 'Black Angus Slab': 'https://www.mountainproject.com/route/stats/121675932/black-angus-slab', 'Niche Beef': 'https://www.mountainproject.com/route/stats/200400229/niche-beef', 'Black Slab': 'https://www.mountainproject.com/route/stats/200743287/black-slab', 'Cloud 9 from Outer Space': 'https://www.mountainproject.com/route/stats/200286074/cloud-9-from-outer-space', 'Black Angus': 'https://www.mountainproject.com/route/stats/107952266/black-angus', 'Sloper City': 'https://www.mountainproject.com/route/stats/106387913/sloper-city', 'The Hidden Crack': 'https://www.mountainproject.com/route/stats/106588042/the-hidden-crack', 'When the Jolisaints Come Compressing Through': 'https://www.mountainproject.com/route/stats/116841622/when-the-jolisaints-come-compressing-through', 'The DiCaprio Arete': 'https://www.mountainproject.com/route/stats/108051924/the-dicaprio-arete', 'Drunkula': 'https://www.mountainproject.com/route/stats/125451724/drunkula', 'Quasi-mono': 'https://www.mountainproject.com/route/stats/125451750/quasi-mono', 'Basketball Diaries': 'https://www.mountainproject.com/route/stats/106960665/basketball-diaries', 'Army of Darkness': 'https://www.mountainproject.com/route/stats/106960681/army-of-darkness', 'Frankenspank': 'https://www.mountainproject.com/route/stats/107921574/frankenspank', 'Queen Amadala': 'https://www.mountainproject.com/route/stats/108050887/queen-amadala', 'Left Hand Of Darkness': 'https://www.mountainproject.com/route/stats/107931862/left-hand-of-darkness', 'Right Hand Of Darkness': 'https://www.mountainproject.com/route/stats/107931875/right-hand-of-darkness', 'Orange Peel': 'https://www.mountainproject.com/route/stats/107611626/orange-peel', 'Trail Mix': 'https://www.mountainproject.com/route/stats/126796510/trail-mix', 'High Step': 'https://www.mountainproject.com/route/stats/107921063/high-step', 'Trail Traverse': 'https://www.mountainproject.com/route/stats/107920457/trail-traverse', 'Middle Man': 'https://www.mountainproject.com/route/stats/107921056/middle-man', 'Slim Pickens': 'https://www.mountainproject.com/route/stats/116841692/slim-pickens', 'The Big Huck': 'https://www.mountainproject.com/route/stats/107920440/the-big-huck', 'Split Decision': 'https://www.mountainproject.com/route/stats/107929219/split-decision', 'High C': 'https://www.mountainproject.com/route/stats/108179099/high-c', 'Totes McGrotes': 'https://www.mountainproject.com/route/stats/108179224/totes-mcgrotes', 'C Sharp': 'https://www.mountainproject.com/route/stats/108179105/c-sharp', "Rizian's Blue Note": 'https://www.mountainproject.com/route/stats/125269626/rizians-blue-note', 'Brown': 'https://www.mountainproject.com/route/stats/120598312/brown', 'Brown SDS': 'https://www.mountainproject.com/route/stats/120598341/brown-sds', 'Brown SDS Direct': 'https://www.mountainproject.com/route/stats/120598407/brown-sds-direct', "Shackleton's Ladder": 'https://www.mountainproject.com/route/stats/125693287/shackletons-ladder', 'Sunakku': 'https://www.mountainproject.com/route/stats/127239144/sunakku', 'El Japoniste': 'https://www.mountainproject.com/route/stats/127239114/el-japoniste', 'Chicken Nugget': 'https://www.mountainproject.com/route/stats/200653963/chicken-nugget', 'Cookies & Crust': 'https://www.mountainproject.com/route/stats/200654021/cookies-crust', 'Gummy Bear Ninja Wizard Turtle Penguin Cyclopes': 'https://www.mountainproject.com/route/stats/200653928/gummy-bear-ninja-wizard-turtle-penguin-cyclopes', 'Sunken Ship': 'https://www.mountainproject.com/route/stats/200654001/sunken-ship', 'The Universe': 'https://www.mountainproject.com/route/stats/200653990/the-universe'}
starting on Death Flakes
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/114444130/death-flakes
starting on Rampage

/tmp/ipykernel_36548/414128257.py:209: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_routes_stats_df = pd.concat([all_routes_stats_df, route_stats_df])

made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106135567/rampage
starting on Press tight
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/112359419/press-tight
starting on The Grim Reacher
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106135578/the-grim-reacher
starting on Circus Trick
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/105717433/circus-trick
starting on Circus Trick Right
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106127755/circus-trick-right
starting on Chaos
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106013793/chaos
starting on Hell Belly Stand
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107957139/hell-belly-stand
starting on Grim Reacher Direct
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/109990646/grim-reacher-direct
starting on Phantom Fighter (Stand)
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/109990741/phantom-fighter-stand
starting on Hell Belly
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106379808/hell-belly
starting on Phantom Fighter
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/105804658/phantom-fighter
starting on Back Alley
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/112386213/back-alley
starting on Back Alley Left
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/112386225/back-alley-left
starting on Center Start
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106115877/center-start
starting on Slots of Fun
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106115881/slots-of-fun
starting on Arete Left Side
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/105804667/arete-left-side
starting on Center Direct
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/109054130/center-direct
starting on Traverse Slots
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/127391870/traverse-slots
starting on Arete Right Side
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/105804671/arete-right-side
starting on Shorter Traverse
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/123952264/shorter-traverse
starting on Bum Steer
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/117402846/bum-steer
starting on Arete Left Side Sit Start
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107931799/arete-left-side-sit-start
starting on Blue Light
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107932354/blue-light
starting on Kick Start
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106115856/kick-start
starting on Leftover Lover
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106115860/leftover-lover
starting on The Crimp Challenge
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106115852/the-crimp-challenge
starting on Lip Traverse
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106115864/lip-traverse
starting on The Pregnancy Arete
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107931744/the-pregnancy-arete
starting on Mr. Trujillo's Big Day
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/105916291/mr-trujillos-big-day
starting on Kick Start Low
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107931731/kick-start-low
starting on Silly Wabbit
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107492628/silly-wabbit
starting on Dyno for Dollars
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106115871/dyno-for-dollars
starting on Double Crimp
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107492624/double-crimp
starting on 1000 LB Caboose
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107931740/1000-lb-caboose
starting on Unknown
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/112401650/unknown
starting on Sticky's Arete
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/121899177/stickys-arete
starting on Shot Hole Traverse
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106870906/shot-hole-traverse
starting on Skinless Dyno
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/121750392/skinless-dyno
starting on schizzle
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106280485/schizzle
starting on Satya
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106203495/satya
starting on Space Needle
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/117339587/space-needle
starting on LSD Saint
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106203523/lsd-saint
starting on Slopey
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107719879/slopey
starting on Descent
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/121743416/descent
starting on Block Shock
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106960653/block-shock
starting on Block Pock
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/120316260/block-pock
starting on Brown Power
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106347517/brown-power
starting on Squashed Arete
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/114096020/squashed-arete
starting on Block Party
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106960646/block-party
starting on Slappin the Block
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107492580/slappin-the-block
starting on Whodunnit
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107492589/whodunnit
starting on Slappin' The Block Sit Start
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107931839/slappin-the-block-sit-start
starting on Five Finger DIscount
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106845593/five-finger-discount
starting on Eric's
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107931852/erics
starting on Short Stuff
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107931756/short-stuff
starting on Mueve se!
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106156004/mueve-se
starting on The Punisher
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107543785/the-punisher
starting on La Derecha
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106148146/la-derecha
starting on Blankety Stand
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107924308/blankety-stand
starting on La Derecha SDS
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/127324725/la-derecha-sds
starting on Blankety Blank
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106148107/blankety-blank
starting on Washing Machine
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107633000/washing-machine
starting on Unnamed V3
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/112911753/unnamed-v3
starting on Washed Up
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106588054/washed-up
starting on Washed Up Extension
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/112807600/washed-up-extension
starting on Hueco Finish
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107924296/hueco-finish
starting on Upwardly Mobile (AKA Hueco Cranks)
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107624646/upwardly-mobile-aka-hueco-cranks
starting on Hueco Traverse
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106115846/hueco-traverse
starting on Wussula
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107936921/wussula
starting on Standula
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107936911/standula
starting on Scoopula
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106588048/scoopula
starting on Pancake Mantle
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107400070/pancake-mantle
starting on Sand Traverse
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106115893/sand-traverse
starting on Black Angus Slab
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/121675932/black-angus-slab
starting on Niche Beef
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/200400229/niche-beef
starting on Black Slab
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/200743287/black-slab
starting on Cloud 9 from Outer Space
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/200286074/cloud-9-from-outer-space
starting on Black Angus
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107952266/black-angus
starting on Sloper City
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106387913/sloper-city
starting on The Hidden Crack
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106588042/the-hidden-crack
starting on When the Jolisaints Come Compressing Through
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/116841622/when-the-jolisaints-come-compressing-through
starting on The DiCaprio Arete
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/108051924/the-dicaprio-arete
starting on Drunkula
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/125451724/drunkula
starting on Quasi-mono
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/125451750/quasi-mono
starting on Basketball Diaries
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106960665/basketball-diaries
starting on Army of Darkness
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/106960681/army-of-darkness
starting on Frankenspank
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107921574/frankenspank
starting on Queen Amadala
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/108050887/queen-amadala
starting on Left Hand Of Darkness
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107931862/left-hand-of-darkness
starting on Right Hand Of Darkness
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107931875/right-hand-of-darkness
starting on Orange Peel
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107611626/orange-peel
starting on Trail Mix
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/126796510/trail-mix
starting on High Step
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107921063/high-step
starting on Trail Traverse
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107920457/trail-traverse
starting on Middle Man
made star_df
made rating_df
made tick_df
made route_stats_df
Finished updating all_routes_stats_df with stats from https://www.mountainproject.com/route/stats/107921056/middle-man
starting on Slim Pickens
made star_df

In [153]:
area_df = csv_df.merge(all_routes_stats_df, how = 'left')
area_df['user.id'] = area_df['user.id'].astype('Int64')

In [ ]:
area_df.to_csv(f"{datetime.now().strftime('%Y%m%d_%H%M%S')}_{AREA_NAME}_area_df_with_stats.csv", index=False)
#area_df = pd.read_csv("20260331_111950_area_df_with_stats.csv")

In [9]:
%ls

20260105_boulder_gender_stats.ipynb
20260331_111950_area_df_with_stats.csv
20260331_111959_unique_user_df.csv
20260331_125929_user_info_df.csv
20260331_175013_area_df_with_user_info.csv
CLAUDE.md
route_stats_cache.pkl
user_info_cache.pkl

In [ ]:
unique_user_df, all_user_dict = make_all_user_dict(area_df = area_df)

Unique users found: 2029

In [ ]:
unique_user_df.to_csv(f"{datetime.now().strftime('%Y%m%d_%H%M%S')}_{AREA_NAME}_unique_user_df.csv", index=False)

In [ ]:

# This is for if the cache is corrupted
#  if os.path.exists('user_info_cache.pkl'):
#       os.remove('user_info_cache.pkl')
#       print("Deleted corrupted cache.")



# This is for if I got booted out of requesting information from MountainProject, so I can remove failed users from the cache and try again. 
# remove_failed_users_from_cache(dry_run=False)

In [ ]:


all_user_dict = fill_user_dict_with_info(all_user_dict)

Resuming — 611 users already cached.
Skipping user 10795 (already cached)
Skipping user 105841142 (already cached)
Ivano Del Piccolo: line_list is empty
Skipping user 106201630 (already cached)
Skipping user 106484139 (already cached)
kiff: line_list is empty
Skipping user 106709875 (already cached)
Skipping user 106827872 (already cached)
Skipping user 106839278 (already cached)
Skipping user 106899065 (already cached)
Skipping user 107102487 (already cached)
Skipping user 107147681 (already cached)
Skipping user 107798616 (already cached)
Skipping user 108809388 (already cached)
Skipping user 109227367 (already cached)
Skipping user 109520650 (already cached)
Skipping user 109527937 (already cached)
Skipping user 110698353 (already cached)
Skipping user 110708951 (already cached)
Skipping user 110752881 (already cached)
Skipping user 110869349 (already cached)
Skipping user 110944243 (already cached)
Skipping user 110966666 (already cached)
Skipping user 111129685 (already cached)
Skipping user 111277975 (already cached)
Skipping user 111704941 (already cached)
Skipping user 111746562 (already cached)
Skipping user 111773187 (already cached)
Skipping user 111876911 (already cached)
Skipping user 111938836 (already cached)
Skipping user 112002192 (already cached)
Skipping user 112228655 (already cached)
Skipping user 112270615 (already cached)
Skipping user 112309405 (already cached)
Skipping user 112421798 (already cached)
Greg Lee: line_list is empty
Skipping user 200112001 (already cached)
Skipping user 200117437 (already cached)
Skipping user 200137026 (already cached)
Skipping user 200150045 (already cached)
Skipping user 200158244 (already cached)
Skipping user 200170545 (already cached)
Skipping user 200171202 (already cached)
Zachary Tan: line_list is empty
Skipping user 200190185 (already cached)
Skipping user 200194181 (already cached)
Skipping user 200205462 (already cached)
Skipping user 200222161 (already cached)
Skipping user 200232501 (already cached)
Skipping user 200251964 (already cached)
Skipping user 200256148 (already cached)
Skipping user 200258129 (already cached)
Skipping user 200261293 (already cached)
Pallav Kosuri: line_list is empty
Skipping user 200265263 (already cached)
Troy Canfield: line_list is empty
Skipping user 200287293 (already cached)
Skipping user 200293334 (already cached)
Skipping user 200326525 (already cached)
Skipping user 200340991 (already cached)
Skipping user 200344008 (already cached)
Ben Murdock: line_list is empty
Skipping user 200370793 (already cached)
Skipping user 200372878 (already cached)
Nick Butterfield: line_list is empty
Elijah Salas: line_list is empty
Daniel Wilder: line_list is empty
Skipping user 200394173 (already cached)
Skipping user 200424745 (already cached)
Skipping user 200425475 (already cached)
Skipping user 200427236 (already cached)
Isaac Young: line_list is empty
Skipping user 200450441 (already cached)
Skipping user 200467423 (already cached)
Skipping user 200474418 (already cached)
Skipping user 200492380 (already cached)
James Braithwaite: line_list is empty
Skipping user 200594520 (already cached)
Skipping user 200613389 (already cached)
Skipping user 200621659 (already cached)
John Thompson: line_list is empty
Sage Frontella: line_list is empty
Skipping user 200657066 (already cached)
Peter Kroner: line_list is empty
Skipping user 200672583 (already cached)
Zach Kauffman: line_list is empty
Aidan Fielding: line_list is empty
Isaac Hangdogger: line_list is empty
Skipping user 200717675 (already cached)
Skipping user 200720041 (already cached)
Skipping user 200735334 (already cached)
Skipping user 200736572 (already cached)
Skipping user 200737601 (already cached)
Kai Ball: line_list is empty
Theo Murray: line_list is empty
Ben Fielding: line_list is empty
Skipping user 200805904 (already cached)
jjonas 1470: line_list is empty
Matt Nearman: line_list is empty
Reese Epper: line_list is empty
Lance Buckner: line_list is empty
Derek Kober: line_list is empty
Samantha Hansen: line_list is empty
Ryan Meadows: line_list is empty
Skipping user 201037780 (already cached)
Skipping user 201073062 (already cached)
Skipping user 201073238 (already cached)
Skipping user 201076046 (already cached)
Branden Whitehead: line_list is empty
Peyton Pierce: line_list is empty
Ethan Shupe: line_list is empty
Charlie Welch: line_list is empty
Andre Christenson: line_list is empty
Austin Mitchell: line_list is empty
Thomas Maloney: line_list is empty
Skipping user 201224911 (already cached)
Skipping user 201227916 (already cached)
Ana Bucko: line_list is empty
Logan Cayton: line_list is empty
Skipping user 201332613 (already cached)
Skipping user 201362192 (already cached)
Tess Terry: line_list is empty
Cooper Wilmot: line_list is empty
Patrick Welsh: line_list is empty
Christian Ford: line_list is empty
Skipping user 201446773 (already cached)
Skipping user 201475628 (already cached)
Conner Driver: line_list is empty
Skipping user 201484104 (already cached)
ella roelker: line_list is empty
Michael Moore: line_list is empty
Quintin Calcott: line_list is empty
Claire Lukas: line_list is empty
Skipping user 201626456 (already cached)
Vincent Tremblay: line_list is empty
Simon Akers: line_list is empty
Alex Perkins: line_list is empty
Skipping user 201717014 (already cached)
Toby Glick: line_list is empty
Skipping user 201730853 (already cached)
Oliver Servais: line_list is empty
Wyatt Murphy: line_list is empty
Zane Long: line_list is empty
Max Williams: line_list is empty
Jackson Houghtaling: line_list is empty
Annabelle Maciak: line_list is empty
Skipping user 15110 (already cached)
Skipping user 105841498 (already cached)
Skipping user 105886042 (already cached)
Skipping user 105934987 (already cached)
Skipping user 106074882 (already cached)
Skipping user 106139652 (already cached)
Skipping user 106822061 (already cached)
Skipping user 107452553 (already cached)
Skipping user 108273603 (already cached)
Michael915: line_list is empty
FromFangorn: line_list is empty
Skipping user 200253169 (already cached)
Tanguy Marquis: line_list is empty
Skipping user 200488460 (already cached)
Skipping user 200757860 (already cached)
Skipping user 200918621 (already cached)
Skipping user 201066317 (already cached)
Skipping user 107329642 (already cached)
Skipping user 105941791 (already cached)
Skipping user 106493154 (already cached)
Paul Robertson: line_list is empty
Samuel Peccoud: line_list is empty
Luke Miller: line_list is empty
Skipping user 10116 (already cached)
Dave Chenault: line_list is empty
Skipping user 12525 (already cached)
Skipping user 105788964 (already cached)
Skipping user 105791779 (already cached)
Andrew Vojslavek: line_list is empty
Skipping user 105844582 (already cached)
Skipping user 105884543 (already cached)
Skipping user 105912797 (already cached)
Skipping user 105914958 (already cached)
Skipping user 105917266 (already cached)
Tony Brengosz: line_list is empty
Skipping user 105980469 (already cached)
Orphaned: line_list is empty
Skipping user 106047496 (already cached)
Skipping user 106074561 (already cached)
Skipping user 106084185 (already cached)
Skipping user 106113739 (already cached)
Skipping user 106121156 (already cached)
Skipping user 106137822 (already cached)
Skipping user 106157684 (already cached)
Tim Gibson: line_list is empty
Skipping user 106265516 (already cached)
Skipping user 106380853 (already cached)
Skipping user 106385871 (already cached)
Skipping user 106413021 (already cached)
Jeremy.M: line_list is empty
Conor Byrne: line_list is empty
Skipping user 106526755 (already cached)
Skipping user 106604110 (already cached)
Skipping user 106662570 (already cached)
Skipping user 106821828 (already cached)
Skipping user 106920443 (already cached)
Skipping user 106939061 (already cached)
Jeremy Jacobsen: line_list is empty
Skipping user 107016396 (already cached)
Skipping user 107016978 (already cached)
Skipping user 107068235 (already cached)
Skipping user 107096937 (already cached)
Skipping user 107134274 (already cached)
Karthik Sonty: line_list is empty
Skipping user 107228211 (already cached)
Skipping user 107419681 (already cached)
Skipping user 107431114 (already cached)
Skipping user 107514810 (already cached)
Skipping user 107521255 (already cached)
Skipping user 107533665 (already cached)
Skipping user 107638109 (already cached)
Skipping user 107732460 (already cached)
Chappy: line_list is empty
Skipping user 107837626 (already cached)
Skipping user 107842737 (already cached)
Skipping user 107979322 (already cached)
Skipping user 107986480 (already cached)
Skipping user 108037452 (already cached)
Skipping user 108045940 (already cached)
Skipping user 108085357 (already cached)
Skipping user 108211714 (already cached)
Skipping user 108255903 (already cached)
Skipping user 108386412 (already cached)
Skipping user 108454711 (already cached)
Skipping user 108465688 (already cached)
Skipping user 108766448 (already cached)
Skipping user 109116607 (already cached)
Skipping user 109264635 (already cached)
Skipping user 109423410 (already cached)
Skipping user 109557838 (already cached)
Skipping user 109564564 (already cached)
Skipping user 109591535 (already cached)
Skipping user 109708911 (already cached)
Skipping user 110275824 (already cached)
JerryBob Curtis: line_list is empty
Skipping user 110506064 (already cached)
Skipping user 110643907 (already cached)
Skipping user 110708263 (already cached)
Patrick Bodnar: line_list is empty
Skipping user 110940145 (already cached)
Skipping user 111094648 (already cached)
Skipping user 111146447 (already cached)
Skipping user 111151566 (already cached)
Skipping user 111313853 (already cached)
Skipping user 111315175 (already cached)
Skipping user 111347304 (already cached)
Jason Bynum: line_list is empty
Skipping user 111610817 (already cached)
Skipping user 111670378 (already cached)
Skipping user 111742479 (already cached)
Skipping user 111777299 (already cached)
Bobby Seo: line_list is empty
Skipping user 111932954 (already cached)
Thomas Martin 2: line_list is empty
Skipping user 111972029 (already cached)
Skipping user 112013963 (already cached)
Skipping user 112079157 (already cached)
Carlo Nasisse: line_list is empty
Skipping user 112142214 (already cached)
Skipping user 112207296 (already cached)
Skipping user 112396053 (already cached)
Skipping user 112447002 (already cached)
Nicholas Shearer: line_list is empty
Skipping user 112501386 (already cached)
Skipping user 112853491 (already cached)
Tucker Young: line_list is empty
Skipping user 112896794 (already cached)
Jackson Birrell: line_list is empty
Skipping user 200033518 (already cached)
Skipping user 200036989 (already cached)
Skipping user 200060560 (already cached)
Skipping user 200081196 (already cached)
Skipping user 200088786 (already cached)
Skipping user 200094521 (already cached)
Jake Sobelman: line_list is empty
Skipping user 200109347 (already cached)
Skipping user 200114191 (already cached)
Skipping user 200124470 (already cached)
Taylor Stoecklin: line_list is empty
Skipping user 200149370 (already cached)
Skipping user 200170080 (already cached)
Skipping user 200177019 (already cached)
Skipping user 200179705 (already cached)
Skipping user 200200867 (already cached)
Skipping user 200202771 (already cached)
Cameron Jeffords: line_list is empty
Skipping user 200231547 (already cached)
Skipping user 200236355 (already cached)
Skipping user 200262442 (already cached)
Skipping user 200273423 (already cached)
Melanie Robertson: line_list is empty
Future Mouse: line_list is empty
Skipping user 200327345 (already cached)
Skipping user 200344476 (already cached)
Skipping user 200348225 (already cached)
Adrian Smith: line_list is empty
Skipping user 200358665 (already cached)
Skipping user 200361198 (already cached)
Cory Best: line_list is empty
Skipping user 200365214 (already cached)
Skipping user 200367019 (already cached)
Arnaud Bayol: line_list is empty
Skipping user 200381808 (already cached)
Skipping user 200387899 (already cached)
Skipping user 200394444 (already cached)
Skipping user 200394785 (already cached)
Cameron B: line_list is empty
Skipping user 200418542 (already cached)
Skipping user 200430991 (already cached)
Adam C: line_list is empty
Aidan Jones: line_list is empty
Eddy Long: line_list is empty
Skipping user 200460231 (already cached)
Skipping user 200487797 (already cached)
Skipping user 200492967 (already cached)
Skipping user 200495520 (already cached)
Skipping user 200507224 (already cached)
Skipping user 200508044 (already cached)
Grant Burns: line_list is empty
Benj Bidinger: line_list is empty
Cole Birrer: line_list is empty
Skipping user 200555916 (already cached)
Skipping user 200569839 (already cached)
Skipping user 200574010 (already cached)
Sylvain Hugon: line_list is empty
Jarrett Daffern: line_list is empty
Skipping user 200636161 (already cached)
Skipping user 200647528 (already cached)
Skipping user 200648769 (already cached)
Skipping user 200651979 (already cached)
Skipping user 200654713 (already cached)
Ryan Tse: line_list is empty
Skipping user 200675556 (already cached)
Skipping user 200677940 (already cached)
Michael Concannon: line_list is empty
Jack Mason: line_list is empty
Skipping user 200723070 (already cached)
C Monkey: line_list is empty
Skipping user 200734580 (already cached)
Mateo W: line_list is empty
Denzil Rogers: line_list is empty
Dean Allison: line_list is empty
Stuart Rinehart: line_list is empty
Anderson Songer: line_list is empty
Barron Bronson: line_list is empty
Cade Smith: line_list is empty
B-rock Chase: line_list is empty
Skipping user 201263880 (already cached)
Skipping user 201375449 (already cached)
Skipping user 201459502 (already cached)
Skipping user 201496394 (already cached)
Karl Winschel: line_list is empty
Skipping user 201518887 (already cached)
Drew hartfield: line_list is empty
Dustin V: line_list is empty
Reed V: line_list is empty
Vemund Vestreng: line_list is empty
Max Meixensperger: line_list is empty
Chance Hampton: line_list is empty
Scott Blunk: line_list is empty
Devin Busb: line_list is empty
Gabriel O'Crowley: line_list is empty
Luke Scanlan: line_list is empty
Braden Duce: line_list is empty
Booth O'Connell: line_list is empty
Brennanymous: line_list is empty
Skipping user 105822848 (already cached)
Justin Tschinkel: line_list is empty
Skipping user 200708396 (already cached)
Skipping user 299139 (already cached)
Tristan Perry: line_list is empty
Skipping user 106024225 (already cached)
Skipping user 106046172 (already cached)
chris schulte: line_list is empty
Skipping user 106380108 (already cached)
Skipping user 108165356 (already cached)
Skipping user 109597098 (already cached)
Skipping user 112049106 (already cached)
Skipping user 200232512 (already cached)
Liam Foster: line_list is empty
Adrian Velasquez: line_list is empty
Skipping user 106456455 (already cached)
Skipping user 110304563 (already cached)
Skipping user 200629561 (already cached)
Skipping user 14346 (already cached)
Luke Olson: line_list is empty
Skipping user 107457280 (already cached)
Hot Cuppa: line_list is empty
Skipping user 107734618 (already cached)
Skipping user 107909507 (already cached)
Skipping user 108026328 (already cached)
Skipping user 108141805 (already cached)
Skipping user 108242742 (already cached)
Skipping user 108411681 (already cached)
Skipping user 108432977 (already cached)
Skipping user 109212068 (already cached)
Skipping user 109677323 (already cached)
Skipping user 110239422 (already cached)
Skipping user 110701735 (already cached)
Skipping user 111128710 (already cached)
Skipping user 111256590 (already cached)
Skipping user 111273796 (already cached)
Skipping user 111531597 (already cached)
Skipping user 112212516 (already cached)
Skipping user 112569750 (already cached)
Skipping user 200004298 (already cached)
Skipping user 200008001 (already cached)
Skipping user 200067286 (already cached)
Skipping user 200069219 (already cached)
Logan L: line_list is empty
Skipping user 200094644 (already cached)
Chris Jankowski: line_list is empty
Ryan Copley: line_list is empty
Skipping user 200178865 (already cached)
Ali Moxley: line_list is empty
Nate Blehm: line_list is empty
Skipping user 200284087 (already cached)
Skipping user 200313075 (already cached)
Ryan Choque: line_list is empty
Cassey Smith: line_list is empty
Skipping user 200370264 (already cached)
Gavin Baker: line_list is empty
Collin Gilmore: line_list is empty
Skipping user 200407813 (already cached)
Skipping user 200426904 (already cached)
Skipping user 200443117 (already cached)
Parker Izatt: line_list is empty
Skipping user 200567165 (already cached)
Jake R: line_list is empty
Collin Rasmussen: line_list is empty
Italia Torres: line_list is empty
Skipping user 200666779 (already cached)
Skipping user 200673614 (already cached)
Chris Johnson: line_list is empty
Shelby Wolfe: line_list is empty
Skipping user 200683266 (already cached)
Rachel Zuckerman: line_list is empty
Ty Sweeney: line_list is empty
Damon Ashcraft: line_list is empty
Nima Sarram: line_list is empty
Matt Freie: line_list is empty
Austin Jenne: line_list is empty
Skipping user 200986495 (already cached)
Dawson Brown: line_list is empty
Felix Serlin: line_list is empty
Campbell B: line_list is empty
Emerson Welch: line_list is empty
Nicole Dhar: line_list is empty
Grace Maridyth: line_list is empty
Alex Mata: line_list is empty
Skipping user 201130872 (already cached)
Skipping user 201141173 (already cached)
Robert Denton-Smith: line_list is empty
The Spirit of Greg Molica: line_list is empty
Joey Skiba: line_list is empty
Natalie Hall: line_list is empty
Gwyn Pleatman: line_list is empty
Skipping user 201317262 (already cached)
Matt Monfils: line_list is empty
Trey Corrigan: line_list is empty
Jordan Pawlowski: line_list is empty
Julian Anchondo: line_list is empty
Skipping user 201366387 (already cached)
Lily Fox: line_list is empty
Skipping user 201502283 (already cached)
Charlie Zwierzchowski: line_list is empty
Emily Lanter: line_list is empty
Brendan Goodbred: line_list is empty
Em Watson: line_list is empty
Adam Rosser: line_list is empty
Emily Elder: line_list is empty
Donovan Theurer: line_list is empty
Anonymous: line_list is empty
Anonymous: line_list is empty
Skipping user 108070812 (already cached)
Skipping user 200172768 (already cached)
Dan Dutton: line_list is empty
Skipping user 200536067 (already cached)
Skipping user 200584576 (already cached)
Simon Wagner: line_list is empty
Tiffany Dang: line_list is empty
Nathan Kigerl: line_list is empty
Skipping user 14213 (already cached)
Skipping user 7061789 (already cached)
Kensie Sempert: line_list is empty
Skipping user 105794408 (already cached)
Skipping user 105797286 (already cached)
Skipping user 105810061 (already cached)
Skipping user 105815147 (already cached)
Skipping user 105936209 (already cached)
Skipping user 105941332 (already cached)
Skipping user 105952525 (already cached)
Skipping user 105973110 (already cached)
Skipping user 106022334 (already cached)
Skipping user 106045902 (already cached)
Skipping user 106055829 (already cached)
Skipping user 106071626 (already cached)
Skipping user 106074136 (already cached)
Skipping user 106199442 (already cached)
Skipping user 106223263 (already cached)
Skipping user 106229519 (already cached)
Skipping user 106238929 (already cached)
Skipping user 106268558 (already cached)
Skipping user 106308715 (already cached)
Skipping user 106430658 (already cached)
Chris Mak: line_list is empty
Skipping user 106461972 (already cached)
Skipping user 106558554 (already cached)
Skipping user 106610639 (already cached)
Marc Daubert: line_list is empty
Skipping user 106714931 (already cached)
Skipping user 106740073 (already cached)
Brianluce: line_list is empty
Skipping user 106755421 (already cached)
Skipping user 106866450 (already cached)
Skipping user 106879184 (already cached)

In [146]:
user_info_df = pd.DataFrame(all_user_dict.values())

# if the information request fails for some users, their gender will not be guessed so this needs to be pulled separately. 
user_info_df = fill_missing_guessed_gender(user_info_df)

print(user_info_df.shape)
user_info_df.head()

Filled guessed_gender for 0 rows.
(2029, 8)

,user_ID,user_name,user_URL,request_date,location,age_at_request_date,listed_gender,guessed_gender
0,10795,Craig Quincy,https://www.mountainproject.com/user/10795/cra...,2026.0,"Louisville, CO",NaN,Male,male
1,105841142,kzoo,https://www.mountainproject.com/user/105841142...,2026.0,michigan,48.0,Male,unknown
2,106196136,Ivano Del Piccolo,https://www.mountainproject.com/user/106196136...,NaN,None,NaN,None,male
3,106201630,ben jammin,https://www.mountainproject.com/user/106201630...,2026.0,"Moab, UT",41.0,Male,male
4,106484139,Brian Koralewski,https://www.mountainproject.com/user/106484139...,2026.0,"Springville, UT",NaN,Male,male

In [ ]:
user_info_df.to_csv(f"{datetime.now().strftime('%Y%m%d_%H%M%S')}_{AREA_NAME}_user_info_df.csv", index=False)

In [5]:
%ls

20260105_boulder_gender_stats.ipynb
20260331_111950_area_df_with_stats.csv
20260331_111959_unique_user_df.csv
20260331_125929_user_info_df.csv
20260331_175013_area_df_with_user_info.csv
CLAUDE.md
route_stats_cache.pkl
user_info_cache.pkl

In [154]:
area_df = area_df.merge(
    user_info_df[['user_ID', 'user_URL', 'location', 'age_at_request_date', 'listed_gender', 'guessed_gender']],
    left_on='user.id',
    right_on='user_ID',
    how='left'
).drop(columns='user_ID')

area_df.head()

,Route,Location,URL,Avg Stars,Your Stars,Route Type,Rating,Pitches,Length,Area Latitude,...,style,leadStyle,pitches,tick_createdAt,tick_updatedAt,user_URL,location,age_at_request_date,listed_gender,guessed_gender
0,Death Flakes,Chaos Boulder > Big Bend Bouldering Area > Riv...,https://www.mountainproject.com/route/11444413...,3.0,-1,Boulder,V1 R,1,20.0,38.65058,...,,,1.0,2025-04-09T04:29:09.000000Z,2025-04-09T04:29:09.000000Z,https://www.mountainproject.com/user/10795/cra...,"Louisville, CO",NaN,Male,male
1,Death Flakes,Chaos Boulder > Big Bend Bouldering Area > Riv...,https://www.mountainproject.com/route/11444413...,3.0,-1,Boulder,V1 R,1,20.0,38.65058,...,Attempt,,1.0,2023-04-02T23:11:53.000000Z,2023-04-02T23:11:53.000000Z,https://www.mountainproject.com/user/10795/cra...,"Louisville, CO",NaN,Male,male
2,Death Flakes,Chaos Boulder > Big Bend Bouldering Area > Riv...,https://www.mountainproject.com/route/11444413...,3.0,-1,Boulder,V1 R,1,20.0,38.65058,...,Lead,Onsight,1.0,2021-03-31T00:57:57.000000Z,2021-03-31T00:57:57.000000Z,https://www.mountainproject.com/user/105841142...,michigan,48.0,Male,unknown
3,Death Flakes,Chaos Boulder > Big Bend Bouldering Area > Riv...,https://www.mountainproject.com/route/11444413...,3.0,-1,Boulder,V1 R,1,20.0,38.65058,...,,,1.0,2019-05-16T18:55:03.000000Z,2019-05-16T18:55:03.000000Z,https://www.mountainproject.com/user/106196136...,None,NaN,None,male
4,Death Flakes,Chaos Boulder > Big Bend Bouldering Area > Riv...,https://www.mountainproject.com/route/11444413...,3.0,-1,Boulder,V1 R,1,20.0,38.65058,...,NaN,NaN,NaN,NaN,NaN,https://www.mountainproject.com/user/106201630...,"Moab, UT",41.0,Male,male

In [162]:
area_df['likely_gender'] = area_df.apply(assign_likely_gender, axis=1)

In [ ]:
area_df.to_csv(f"{datetime.now().strftime('%Y%m%d_%H%M%S')}_{AREA_NAME}_area_df_with_user_info.csv", index=False)

In [ ]:
# if the information request fails for some users, their gender will not be guessed so this needs to be pulled separately. 

user_info_df = fill_missing_guessed_gender(user_info_df)

Filled guessed_gender for 0 rows.

In [ ]:
'''
2026-03-29 Next steps
- Pick another small climbing area to compare this to, ideally one that I think will have a higher female ratio...maybe near LA? 
        - could try a sub-area of bishop...
        - maybe try Flagstaff Mountain in Boulder
- Figure out what other plots I want to make
        - How good is geneder_guesser at guessing the right gender? Make sure to differentiate between "unknown" and a real mismatch
        - what is the number of engagements (ticks/ratings/stars) each climb has? How many are repeats of the same user and how many are unique users?
        - 
- Make another column in my data frame for gender-to-use, which is the listed_gender if given, or the guessed_gender if listed_gender is None. 
- Add in someway of looking at comments 
- Clean up the code more
        - make sure functions all have explanations and are consistent logic
        - make it so that one function is called and that calls all of the other functions. 
- Try again for the same areas using TheCrag instead - see if the gender ratio changes at all. 
- Figure out how/where to write up a report of my findings
- cite Santamaría L, Mihaljević H. 2018. Comparison and benchmark of name-to-gender inference services. PeerJ Computer Science 4:e156 https://doi.org/10.7717/peerj-cs.156 in regards to genderguesser
'''

'\n2026-03-29 Next steps\n- Pick another small climbing area to compare this to, ideally one that I think will have a higher female ratio...maybe near LA? \n        - could try a sub-area of bishop...\n- Figure out what other plots I want to make\n- Clean up the code more\n        - make sure functions all have explanations and are consistent logic\n        - make it so that one function is called and that calls all of the other functions. \n        - \n'