Finding boulders that were rated highly specifically by women



1.   API call to Mountain Project for boulders in a specific region

2.   For each boulder problem, pull out the user stars, ticks, and grade ratings. 

3.   Combine the above dataframes into one that includes all of the information for that boulder problem. 

4.   Once that has been completed, repeat for all boulder problems. 

5.   Use the combined dataframe for all boulder problems to find the user ID and name of all unique relevant users. 

6.   Pull the user data and make a user personal information database. 

7.   Combine the boulder problem database wtih the user information database. 

8.   Now all of the data is processed together, so I can start analyzing it. 

* How much information do I have on users? How many are missing data, etc
* How well am I guessing the gender of users?  I think the guesser is biased towards names of European descent.
* For each boulder problem, Display rating for overall, male, female, undetermined. 
* Also pull out dataframe of comments from women.
* Do I want to use AI to guess user gender from their comments attached to their ticks?

In [75]:
# Import packages
import climbing_functions
import importlib
importlib.reload(climbing_functions)
# from bs4 import BeautifulSoup # https://beautiful-soup-4.readthedocs.io/en/latest/
# import copy
from datetime import datetime
# import gender_guesser.detector as gender
# import io
# import matplotlib.pyplot as plt
# import numpy as np
import os
import pandas as pd
# import pickle
# import requests # https://requests.readthedocs.io/en/latest/
# import time
# import urllib.parse

In [76]:
#%cd climb_data_code/

In [77]:
# set variable values

HEADERS = {'User-Agent': 'Independent research project - contact: carlybond907@gmail.com'}

# Go to Mountain Project and navigate to climbing area of interest. Open the Find routes button and filter for all routes of interest. 
# In the original use case, filter for all boulder problems.
# The URL needs to be the link to the "export csv" button, so an easy way of doing that is to  right click "export csv" and copy the link.

AREA_NAME = "Vedauwoo_Climbing"
URL = "https://www.mountainproject.com/route-finder-export?diffMaxaid=75260&diffMaxboulder=21700&diffMaxice=38500&diffMaxmixed=65050&diffMaxrock=5500&diffMinaid=70000&diffMinboulder=20000&diffMinice=30000&diffMinmixed=50000&diffMinrock=1800&is_sport_climb=1&is_top_rope=1&is_trad_climb=1&pitches=0&selectedIds=105744307&sort1=area&sort2=rating&stars=0&type=boulder&viewAll=1"

#AREA_NAME = "Happy_Sad_Boulders"
#URL = "https://www.mountainproject.com/route-finder-export?diffMaxaid=75260&diffMaxboulder=21700&diffMaxice=38500&diffMaxmixed=65050&diffMaxrock=5500&diffMinaid=70000&diffMinboulder=20000&diffMinice=30000&diffMinmixed=50000&diffMinrock=1800&is_sport_climb=1&is_top_rope=1&is_trad_climb=1&pitches=0&selectedIds=106094717&sort1=area&sort2=rating&stars=0&type=boulder&viewAll=1"

#AREA_NAME = "Buttermilks"
#URL = "https://www.mountainproject.com/route-finder-export?diffMaxaid=75260&diffMaxboulder=21700&diffMaxice=38500&diffMaxmixed=65050&diffMaxrock=5500&diffMinaid=70000&diffMinboulder=20000&diffMinice=30000&diffMinmixed=50000&diffMinrock=1800&is_sport_climb=1&is_top_rope=1&is_trad_climb=1&pitches=0&selectedIds=105876411&sort1=area&sort2=rating&stars=0&type=boulder&viewAll=1"


#AREA_NAME = "Flagstaff_V5_to_V17"
#URL = "https://www.mountainproject.com/route-finder-export?diffMaxaid=75260&diffMaxboulder=21700&diffMaxice=38500&diffMaxmixed=65050&diffMaxrock=5500&diffMinaid=70000&diffMinboulder=20450&diffMinice=30000&diffMinmixed=50000&diffMinrock=1800&is_sport_climb=1&is_top_rope=1&is_trad_climb=1&pitches=0&selectedIds=105744225&sort1=area&sort2=rating&stars=0&type=boulder&viewAll=1"

#AREA_NAME = "Flagstaff_V0_to_V4"
#URL = "https://www.mountainproject.com/route-finder-export?diffMaxaid=75260&diffMaxboulder=20450&diffMaxice=38500&diffMaxmixed=65050&diffMaxrock=2800&diffMinaid=70000&diffMinboulder=20000&diffMinice=30000&diffMinmixed=50000&diffMinrock=1800&is_sport_climb=1&is_top_rope=1&is_trad_climb=1&pitches=0&selectedIds=105744225&sort1=area&sort2=rating&stars=0&type=boulder&viewAll=1"


#AREA_NAME = "Big_Bend_Bouldering"
#URL = "https://www.mountainproject.com/route-finder-export?diffMaxaid=75260&diffMaxboulder=21700&diffMaxice=38500&diffMaxmixed=65050&diffMaxrock=5500&diffMinaid=70000&diffMinboulder=20000&diffMinice=30000&diffMinmixed=50000&diffMinrock=1800&is_sport_climb=1&is_top_rope=1&is_trad_climb=1&pitches=0&selectedIds=105716862&sort1=area&sort2=rating&stars=0&type=boulder&viewAll=1"

In [78]:
#Create subdirectory

os.makedirs("data", exist_ok=True)  # creates folder if it doesn't exist

In [79]:
csv_df = climbing_functions.retrieve_overview_csv(URL)

# Save overview df
csv_df.to_csv(f"data/{datetime.now().strftime('%Y%m%d_%H%M%S')}_{AREA_NAME}_csv_df.csv", index=False)

CSV converted to pandas df

In [60]:
#%cd data

In [ ]:
#csv_df = pd.read_csv("data/20260402_124733_Flagstaff_V0_to_V4_csv_df.csv")

In [80]:
all_routes_stats_df = climbing_functions.fill_area_df_with_stats(area_df = csv_df)

{'Joy Ride': 'https://www.mountainproject.com/route/stats/106871118/joy-ride', "Sweet Sweet Lovin'": 'https://www.mountainproject.com/route/stats/105764196/sweet-sweet-lovin', 'Jump Start V1': 'https://www.mountainproject.com/route/stats/105764208/jump-start-v1', '10': 'https://www.mountainproject.com/route/stats/112808730/10', 'Lost My Lighter': 'https://www.mountainproject.com/route/stats/117299601/lost-my-lighter', 'Unnamed Warm-ups': 'https://www.mountainproject.com/route/stats/112808687/unnamed-warm-ups', 'Turd Farmer': 'https://www.mountainproject.com/route/stats/106112086/turd-farmer', 'Mantel/Hump, V3': 'https://www.mountainproject.com/route/stats/105764205/mantelhump-v3', 'The Calving Process': 'https://www.mountainproject.com/route/stats/106801286/the-calving-process', 'Unknown  2': 'https://www.mountainproject.com/route/stats/112808597/unknown-2', '6': 'https://www.mountainproject.com/route/stats/112808642/6', 'Emu Dreamer': 'https://www.mountainproject.com/route/stats/112808667/emu-dreamer', "Don't Fence Me In (aka Suzuki Roof)": 'https://www.mountainproject.com/route/stats/106109551/dont-fence-me-in-aka-suzuki-roof', 'Skeavy Bastards': 'https://www.mountainproject.com/route/stats/106749281/skeavy-bastards', 'Little America': 'https://www.mountainproject.com/route/stats/105764199/little-america', 'Turd Farmer Traverse': 'https://www.mountainproject.com/route/stats/106608869/turd-farmer-traverse', '"40. Project"': 'https://www.mountainproject.com/route/stats/106801261/40-project', 'Superficial Man': 'https://www.mountainproject.com/route/stats/112808554/superficial-man', 'Unknown': 'https://www.mountainproject.com/route/stats/106031956/unknown', 'Dogfight': 'https://www.mountainproject.com/route/stats/108255877/dogfight', 'Apostrophe': 'https://www.mountainproject.com/route/stats/106749274/apostrophe', 'Bug Boy Bulge': 'https://www.mountainproject.com/route/stats/112808744/bug-boy-bulge', 'Desparado': 'https://www.mountainproject.com/route/stats/106749263/desparado', '"31. Project"': 'https://www.mountainproject.com/route/stats/106801252/31-project', 'Unknown (approach to Kim)': 'https://www.mountainproject.com/route/stats/121364464/unknown-approach-to-kim', 'The Bistro': 'https://www.mountainproject.com/route/stats/106436992/the-bistro', 'Green With Envy': 'https://www.mountainproject.com/route/stats/106546964/green-with-envy', 'Toadstool': 'https://www.mountainproject.com/route/stats/105989126/toadstool', 'Soul of a Poet': 'https://www.mountainproject.com/route/stats/105872979/soul-of-a-poet', 'The Bear Voo': 'https://www.mountainproject.com/route/stats/106547017/the-bear-voo', 'Cumulus': 'https://www.mountainproject.com/route/stats/106009363/cumulus', 'Heroes Become Weak': 'https://www.mountainproject.com/route/stats/110442425/heroes-become-weak', 'The Gill Seam': 'https://www.mountainproject.com/route/stats/110442406/the-gill-seam', 'Daisy Cutter': 'https://www.mountainproject.com/route/stats/119563317/daisy-cutter', 'Mary': 'https://www.mountainproject.com/route/stats/106506629/mary', 'Jabberwocky': 'https://www.mountainproject.com/route/stats/107088565/jabberwocky', 'Daisy Cutter Assis': 'https://www.mountainproject.com/route/stats/119563350/daisy-cutter-assis', "Skinner's Reprise": 'https://www.mountainproject.com/route/stats/119563469/skinners-reprise', 'Weak Become Heroes': 'https://www.mountainproject.com/route/stats/106100627/weak-become-heroes', 'Tail Spin': 'https://www.mountainproject.com/route/stats/106480899/tail-spin', 'Right Winger': 'https://www.mountainproject.com/route/stats/106019436/right-winger', 'Where the Sidewalk Ends': 'https://www.mountainproject.com/route/stats/106269892/where-the-sidewalk-ends', 'Cupcake': 'https://www.mountainproject.com/route/stats/105814053/cupcake', 'Unknown Crystal Slab': 'https://www.mountainproject.com/route/stats/109818248/unknown-crystal-slab', 'Hand Jam Traverse aka V1 Traverse': 'https://www.mountainproject.com/route/stats/121731234/hand-jam-traverse-aka-v1-traverse', 'Deterioration / Unknown': 'https://www.mountainproject.com/route/stats/114173253/deterioration-unknown', 'Banana Hammock': 'https://www.mountainproject.com/route/stats/106220143/banana-hammock', 'Unknown Mantle': 'https://www.mountainproject.com/route/stats/109818242/unknown-mantle', 'Unnamed Corridor Chockstone 5.11': 'https://www.mountainproject.com/route/stats/201635395/unnamed-corridor-chockstone-511', 'In The Dark': 'https://www.mountainproject.com/route/stats/106438151/in-the-dark', 'Campsite Host Boulder': 'https://www.mountainproject.com/route/stats/111031236/campsite-host-boulder', "Pineapple Doesn't Go On Pizza": 'https://www.mountainproject.com/route/stats/201745712/pineapple-doesnt-go-on-pizza', 'Heel to Toe': 'https://www.mountainproject.com/route/stats/119266118/heel-to-toe', 'Slab Stealer': 'https://www.mountainproject.com/route/stats/106442678/slab-stealer', 'Slab and Grab': 'https://www.mountainproject.com/route/stats/119292704/slab-and-grab', "Murphy's Law": 'https://www.mountainproject.com/route/stats/109818100/murphys-law', 'Blood Sport': 'https://www.mountainproject.com/route/stats/109489309/blood-sport', "Soak'em In Cider": 'https://www.mountainproject.com/route/stats/106220162/soakem-in-cider', 'Sun Up To Sundown': 'https://www.mountainproject.com/route/stats/106438428/sun-up-to-sundown', 'Lucky You': 'https://www.mountainproject.com/route/stats/106442644/lucky-you', 'E-D': 'https://www.mountainproject.com/route/stats/126387280/e-d', 'Shotgun Willy': 'https://www.mountainproject.com/route/stats/113040976/shotgun-willy', 'Tempest': 'https://www.mountainproject.com/route/stats/105756481/tempest', 'The Republic': 'https://www.mountainproject.com/route/stats/108117194/the-republic', 'The Vedajuicer': 'https://www.mountainproject.com/route/stats/105964181/the-vedajuicer', 'Unknown Boulder V0': 'https://www.mountainproject.com/route/stats/124704071/unknown-boulder-v0', 'Cheap Perfume': 'https://www.mountainproject.com/route/stats/111878921/cheap-perfume', 'Cheap Perfume Direct': 'https://www.mountainproject.com/route/stats/111884776/cheap-perfume-direct', 'Classic Splitter': 'https://www.mountainproject.com/route/stats/105971762/classic-splitter', 'Reverse Cowgirl': 'https://www.mountainproject.com/route/stats/111941986/reverse-cowgirl', 'The Biggest Tits in Country Music': 'https://www.mountainproject.com/route/stats/105753949/the-biggest-tits-in-country-music', 'Boneghazi': 'https://www.mountainproject.com/route/stats/111942030/boneghazi', "The Biggest Lips in Rock 'n' Roll": 'https://www.mountainproject.com/route/stats/111942212/the-biggest-lips-in-rock-n-roll', 'Nameless Crack': 'https://www.mountainproject.com/route/stats/119755544/nameless-crack', 'To be deleted - submitted as The Whisper Seep': 'https://www.mountainproject.com/route/stats/201252583/to-be-deleted-submitted-as-the-whisper-seep', 'Desiderata': 'https://www.mountainproject.com/route/stats/105861281/desiderata', 'Soggy Bottom': 'https://www.mountainproject.com/route/stats/106455722/soggy-bottom', 'Cincinnati Sua Slide': 'https://www.mountainproject.com/route/stats/106937009/cincinnati-sua-slide', 'The Hatchet': 'https://www.mountainproject.com/route/stats/106457667/the-hatchet', 'Bombay Hooker': 'https://www.mountainproject.com/route/stats/106533911/bombay-hooker', 'The Bear Flare': 'https://www.mountainproject.com/route/stats/106936959/the-bear-flare', 'Psychoshop': 'https://www.mountainproject.com/route/stats/105867965/psychoshop', 'Guardian': 'https://www.mountainproject.com/route/stats/106169872/guardian', 'The Red Snapper': 'https://www.mountainproject.com/route/stats/106097769/the-red-snapper', 'The Borg': 'https://www.mountainproject.com/route/stats/110467553/the-borg', 'Cement Shoes': 'https://www.mountainproject.com/route/stats/117094290/cement-shoes', 'Uncle Billy': 'https://www.mountainproject.com/route/stats/110462858/uncle-billy', 'Equilibrium': 'https://www.mountainproject.com/route/stats/106039921/equilibrium', 'Sky Line': 'https://www.mountainproject.com/route/stats/106429711/sky-line', 'The Fist Crack aka High School Crush': 'https://www.mountainproject.com/route/stats/106430650/the-fist-crack-aka-high-school-crush', 'Peach Cobbler': 'https://www.mountainproject.com/route/stats/106429732/peach-cobbler', 'Time Quake': 'https://www.mountainproject.com/route/stats/105865800/time-quake', 'Old Dogs New Trick': 'https://www.mountainproject.com/route/stats/105813842/old-dogs-new-trick', 'Digital (aka Sector 54?)': 'https://www.mountainproject.com/route/stats/111930946/digital-aka-sector-54', 'Analog': 'https://www.mountainproject.com/route/stats/105872962/analog', 'Unknown V3+': 'https://www.mountainproject.com/route/stats/113211013/unknown-v3', 'Unknown V3': 'https://www.mountainproject.com/route/stats/113211046/unknown-v3', 'Raspberry Crack': 'https://www.mountainproject.com/route/stats/112145304/raspberry-crack', 'Paths to Gloria': 'https://www.mountainproject.com/route/stats/112145240/paths-to-gloria', 'Mexican Miracle Water': 'https://www.mountainproject.com/route/stats/105838427/mexican-miracle-water', 'Unknown 5.9 Dihedral': 'https://www.mountainproject.com/route/stats/109652920/unknown-59-dihedral', 'Warmup Boulder Left': 'https://www.mountainproject.com/route/stats/109652951/warmup-boulder-left', 'Warmup Boulder Right': 'https://www.mountainproject.com/route/stats/109652956/warmup-boulder-right', 'Unknown Crack to Arete': 'https://www.mountainproject.com/route/stats/109652933/unknown-crack-to-arete', 'Greenhorn Traverse': 'https://www.mountainproject.com/route/stats/105819582/greenhorn-traverse', 'David': 'https://www.mountainproject.com/route/stats/105819587/david', 'Electric Mexican': 'https://www.mountainproject.com/route/stats/105819481/electric-mexican', 'Gladiators': 'https://www.mountainproject.com/route/stats/105989571/gladiators', 'Overganging Arete': 'https://www.mountainproject.com/route/stats/109652942/overganging-arete', 'Super Mexican': 'https://www.mountainproject.com/route/stats/105819488/super-mexican', 'Brown Eyed Girl': 'https://www.mountainproject.com/route/stats/105819561/brown-eyed-girl', 'Unnamed Inversion Roof': 'https://www.mountainproject.com/route/stats/109652911/unnamed-inversion-roof', 'Goliath': 'https://www.mountainproject.com/route/stats/105819592/goliath', 'Niños': 'https://www.mountainproject.com/route/stats/105989109/ninos', 'Remnant Militia': 'https://www.mountainproject.com/route/stats/108940761/remnant-militia', 'Brown Eyed Girl Left': 'https://www.mountainproject.com/route/stats/111916339/brown-eyed-girl-left', 'Wu-tang': 'https://www.mountainproject.com/route/stats/106257963/wu-tang', 'The Sparkling Touch': 'https://www.mountainproject.com/route/stats/105820188/the-sparkling-touch', 'V3+': 'https://www.mountainproject.com/route/stats/107929135/v3', 'Tulip Crack': 'https://www.mountainproject.com/route/stats/105861007/tulip-crack', 'Twistor': 'https://www.mountainproject.com/route/stats/111050044/twistor', 'The Ninja Two Step': 'https://www.mountainproject.com/route/stats/107193508/the-ninja-two-step', 'The Hobgoblin': 'https://www.mountainproject.com/route/stats/105834147/the-hobgoblin', 'The Bag Lady': 'https://www.mountainproject.com/route/stats/106369550/the-bag-lady', 'Eagle Rock Dyno': 'https://www.mountainproject.com/route/stats/123672215/eagle-rock-dyno', 'Seven Levels of Purgatory': 'https://www.mountainproject.com/route/stats/105852692/seven-levels-of-purgatory', 'Thunderstorm is Coming': 'https://www.mountainproject.com/route/stats/105852679/thunderstorm-is-coming', 'Go To a Happy Place aka Sloppy Seconds': 'https://www.mountainproject.com/route/stats/105852664/go-to-a-happy-place-aka-sloppy-seconds', 'Underground Counsel': 'https://www.mountainproject.com/route/stats/107105810/underground-counsel', 'Rasta Pasta': 'https://www.mountainproject.com/route/stats/107105824/rasta-pasta', 'Plain View': 'https://www.mountainproject.com/route/stats/109748459/plain-view', 'Slot Flare Left': 'https://www.mountainproject.com/route/stats/105862704/slot-flare-left', 'Slot Flare Right': 'https://www.mountainproject.com/route/stats/106493810/slot-flare-right', 'Dirty Deeds': 'https://www.mountainproject.com/route/stats/105862698/dirty-deeds', 'Decapitation Roof': 'https://www.mountainproject.com/route/stats/105862708/decapitation-roof', '5.7+ Crack Problem': 'https://www.mountainproject.com/route/stats/106951491/57-crack-problem', 'V1 Slab': 'https://www.mountainproject.com/route/stats/106951496/v1-slab', 'Trojan': 'https://www.mountainproject.com/route/stats/105894624/trojan', 'Asha': 'https://www.mountainproject.com/route/stats/105894634/asha', 'Spirits Rebellious': 'https://www.mountainproject.com/route/stats/105880270/spirits-rebellious', 'Tugging Softly': 'https://www.mountainproject.com/route/stats/105880256/tugging-softly', 'Monsters Incorporated': 'https://www.mountainproject.com/route/stats/105886048/monsters-incorporated', 'Layback Flake': 'https://www.mountainproject.com/route/stats/105989434/layback-flake', 'Toilet Bowl': 'https://www.mountainproject.com/route/stats/105989447/toilet-bowl', 'Right Slab': 'https://www.mountainproject.com/route/stats/105989477/right-slab', 'Left Slab': 'https://www.mountainproject.com/route/stats/105989462/left-slab', 'Unknown flared crack': 'https://www.mountainproject.com/route/stats/105989947/unknown-flared-crack', 'Unnamed Scrappy Crack': 'https://www.mountainproject.com/route/stats/105943525/unnamed-scrappy-crack', 'Shanty Shack': 'https://www.mountainproject.com/route/stats/112058580/shanty-shack', 'Lattice Action (formerly The Crap Artist)': 'https://www.mountainproject.com/route/stats/105943519/lattice-action-formerly-the-crap-artist', 'Chill in Wyoming': 'https://www.mountainproject.com/route/stats/124977506/chill-in-wyoming', 'New Shoes': 'https://www.mountainproject.com/route/stats/105972864/new-shoes', 'Meat Milkshake': 'https://www.mountainproject.com/route/stats/106786565/meat-milkshake', 'Lois': 'https://www.mountainproject.com/route/stats/105972893/lois', 'Gut Bomb': 'https://www.mountainproject.com/route/stats/106833082/gut-bomb', 'One in Three Chance of Getting Your Dick Ripped Off': 'https://www.mountainproject.com/route/stats/106148830/one-in-three-chance-of-getting-your-dick-ripped-off', 'Warmup No. 3': 'https://www.mountainproject.com/route/stats/109436146/warmup-no-3', 'Warmup No. 4': 'https://www.mountainproject.com/route/stats/109436151/warmup-no-4', 'Karl': 'https://www.mountainproject.com/route/stats/106226407/karl', 'Warmup No. 1': 'https://www.mountainproject.com/route/stats/109436123/warmup-no-1', 'Knives Out': 'https://www.mountainproject.com/route/stats/119330415/knives-out', 'Hand Banana': 'https://www.mountainproject.com/route/stats/106031924/hand-banana', 'Simiantics': 'https://www.mountainproject.com/route/stats/106032807/simiantics', 'Warmup No. 2': 'https://www.mountainproject.com/route/stats/109436135/warmup-no-2', 'Mr. Wong Burger': 'https://www.mountainproject.com/route/stats/106031930/mr-wong-burger', 'Thin Red Line': 'https://www.mountainproject.com/route/stats/106153478/thin-red-line', 'September Majesty': 'https://www.mountainproject.com/route/stats/202275250/september-majesty', 'Diagnol Offwidth': 'https://www.mountainproject.com/route/stats/122377703/diagnol-offwidth', "That Dog Just Ain't Gonna Hunt": 'https://www.mountainproject.com/route/stats/106658283/that-dog-just-aint-gonna-hunt', 'Leaning Block V4': 'https://www.mountainproject.com/route/stats/106953115/leaning-block-v4', 'Overhanging V5': 'https://www.mountainproject.com/route/stats/106953107/overhanging-v5', 'Roof V5': 'https://www.mountainproject.com/route/stats/106955231/roof-v5', 'Arete V5': 'https://www.mountainproject.com/route/stats/123645213/arete-v5', 'V6 Lip': 'https://www.mountainproject.com/route/stats/106955241/v6-lip', 'For the Commuter': 'https://www.mountainproject.com/route/stats/109653739/for-the-commuter', 'Corridor Crack': 'https://www.mountainproject.com/route/stats/106863364/corridor-crack', 'Chocolate Hotdog': 'https://www.mountainproject.com/route/stats/106788669/chocolate-hotdog', 'The Egg Crack': 'https://www.mountainproject.com/route/stats/105831395/the-egg-crack', 'Haas Offwidth': 'https://www.mountainproject.com/route/stats/105831388/haas-offwidth', 'The Eliminate Inversion Adventure': 'https://www.mountainproject.com/route/stats/106480909/the-eliminate-inversion-adventure', 'Wicked': 'https://www.mountainproject.com/route/stats/106830325/wicked', 'Short 5.9 BP Crack': 'https://www.mountainproject.com/route/stats/105831406/short-59-bp-crack', 'Tall 5.9 BP': 'https://www.mountainproject.com/route/stats/105831433/tall-59-bp', 'Crack Rock': 'https://www.mountainproject.com/route/stats/126754940/crack-rock', 'Unknown Face': 'https://www.mountainproject.com/route/stats/120854686/unknown-face', "Jordan's Seam": 'https://www.mountainproject.com/route/stats/105831399/jordans-seam', "Jay's Got Wood": 'https://www.mountainproject.com/route/stats/105831425/jays-got-wood', 'The Relocation Roof': 'https://www.mountainproject.com/route/stats/105830498/the-relocation-roof', 'North Corner Layback': 'https://www.mountainproject.com/route/stats/105831416/north-corner-layback', "Blair's V2": 'https://www.mountainproject.com/route/stats/109713192/blairs-v2', 'The Anteater': 'https://www.mountainproject.com/route/stats/109713338/the-anteater', "Blair's V6": 'https://www.mountainproject.com/route/stats/109713201/blairs-v6', "Blair's V7": 'https://www.mountainproject.com/route/stats/109713212/blairs-v7', 'The Bayesian Algorithm': 'https://www.mountainproject.com/route/stats/109713224/the-bayesian-algorithm', "John's Meditation Traverse": 'https://www.mountainproject.com/route/stats/109713206/johns-meditation-traverse', 'Le Petit Splitter': 'https://www.mountainproject.com/route/stats/119816931/le-petit-splitter', 'Ladder Blocks': 'https://www.mountainproject.com/route/stats/118959553/ladder-blocks', 'Fingers in a Hallway': 'https://www.mountainproject.com/route/stats/118959436/fingers-in-a-hallway', 'Nubbins': 'https://www.mountainproject.com/route/stats/118959506/nubbins', 'Buck Shot': 'https://www.mountainproject.com/route/stats/106789650/buck-shot', 'Mista Lova Lova': 'https://www.mountainproject.com/route/stats/121397090/mista-lova-lova', 'University of Mars': 'https://www.mountainproject.com/route/stats/105957555/university-of-mars', 'Crack Named Sue': 'https://www.mountainproject.com/route/stats/105865539/crack-named-sue', 'Mama Got Squeezed': 'https://www.mountainproject.com/route/stats/121297537/mama-got-squeezed', 'Jaws': 'https://www.mountainproject.com/route/stats/106058914/jaws', 'Spider Killer': 'https://www.mountainproject.com/route/stats/106058887/spider-killer', 'Philly Cheesesteak': 'https://www.mountainproject.com/route/stats/121760388/philly-cheesesteak', 'Where The Wild Things Are': 'https://www.mountainproject.com/route/stats/105824300/where-the-wild-things-are', 'Eight Ounces To Freedom': 'https://www.mountainproject.com/route/stats/105824309/eight-ounces-to-freedom', 'Cracked Egg Boulder': 'https://www.mountainproject.com/route/stats/106236363/cracked-egg-boulder', 'Taxman': 'https://www.mountainproject.com/route/stats/112128306/taxman', 'Organic Slab': 'https://www.mountainproject.com/route/stats/106553110/organic-slab', "Implants In A Pink, Multi-functional Buc-ee's Tank": 'https://www.mountainproject.com/route/stats/201059569/implants-in-a-pink-multi-functional-buc-ees-tank', 'V2': 'https://www.mountainproject.com/route/stats/109735032/v2', 'Building Blocks': 'https://www.mountainproject.com/route/stats/106551361/building-blocks', "Scared Money Can't Win": 'https://www.mountainproject.com/route/stats/106553127/scared-money-cant-win', 'Barbed Wire': 'https://www.mountainproject.com/route/stats/106553135/barbed-wire', 'Erotic States of Mind': 'https://www.mountainproject.com/route/stats/106553119/erotic-states-of-mind', 'Hasselhoff Dyno': 'https://www.mountainprojec

In [81]:
all_routes_stats_df

,star_id,score,star_createdAt,star_updatedAt,user.id,user.name,rating_id,allRatings,boulderRating,safteyRating,...,tick_id,tick_date,comment,style,leadStyle,pitches,tick_createdAt,tick_updatedAt,Route,rockRating
0,NaN,NaN,NaN,NaN,10795,Craig Quincy,NaN,NaN,NaN,NaN,...,200741538.0,"Apr 8, 2025, 12:00 am",None,,,1.0,2025-04-09T04:29:09.000000Z,2025-04-09T04:29:09.000000Z,Death Flakes,NaN
1,NaN,NaN,NaN,NaN,10795,Craig Quincy,NaN,NaN,NaN,NaN,...,123957986.0,"Apr 2, 2023, 12:00 am",Half way,Attempt,,1.0,2023-04-02T23:11:53.000000Z,2023-04-02T23:11:53.000000Z,Death Flakes,NaN
2,36863921.0,4.0,2021-03-31T00:58:00.000000Z,2021-03-31T00:58:00.000000Z,105841142,kzoo,NaN,NaN,NaN,NaN,...,120465382.0,"Mar 30, 2021, 12:00 am",,Lead,Onsight,1.0,2021-03-31T00:57:57.000000Z,2021-03-31T00:57:57.000000Z,Death Flakes,NaN
3,22621623.0,4.0,2019-05-16T18:55:11.000000Z,2019-05-16T18:55:11.000000Z,106196136,Ivano Del Piccolo,NaN,NaN,NaN,NaN,...,116981808.0,"May 16, 2019, 12:00 am",None,,,1.0,2019-05-16T18:55:03.000000Z,2019-05-16T18:55:03.000000Z,Death Flakes,NaN
4,46197554.0,4.0,2022-01-18T01:23:33.000000Z,2022-01-18T01:23:33.000000Z,106201630,ben jammin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Death Flakes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,75831031.0,3.0,2023-10-15T04:04:06.000000Z,2023-10-15T04:04:06.000000Z,201661903,Jack Leever,2470663.0,[V2],20200.0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nail Bed,NaN
1,76922999.0,3.0,2023-10-31T23:44:35.000000Z,2023-10-31T23:44:35.000000Z,201693964,Pike Somlyay,NaN,NaN,NaN,NaN,...,125243726.0,"Mar 25, 2023, 12:00 am",,Attempt,,1.0,2023-10-31T23:45:08.000000Z,2023-10-31T23:45:08.000000Z,Nail Bed,NaN
2,87127526.0,1.0,2024-04-12T16:47:39.000000Z,2024-04-12T16:47:39.000000Z,<NA>,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nail Bed,NaN
0,75830067.0,5.0,2023-10-15T03:46:31.000000Z,2023-10-15T03:46:31.000000Z,201661903,Jack Leever,2470650.0,[V4-5],20450.0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jack's Burden,NaN
1,92726294.0,1.0,2024-06-26T20:44:12.000000Z,2024-06-26T20:44:12.000000Z,<NA>,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jack's Burden,NaN

In [82]:
area_df = csv_df.merge(all_routes_stats_df, how = 'left')
area_df['user.id'] = area_df['user.id'].astype('Int64')

In [83]:
area_df.to_csv(f"data/{datetime.now().strftime('%Y%m%d_%H%M%S')}_{AREA_NAME}_area_df_with_stats.csv", index=False)
#area_df = pd.read_csv("20260331_111950_area_df_with_stats.csv")

In [84]:
unique_user_df, all_user_dict = climbing_functions.make_all_user_dict(area_df=area_df, area_name=AREA_NAME)

Unique users found: 1110

In [85]:
unique_user_df.to_csv(f"data/{datetime.now().strftime('%Y%m%d_%H%M%S')}_{AREA_NAME}_unique_user_df.csv", index=False)

In [86]:

# This is for if the cache is corrupted
#  if os.path.exists('user_info_cache.pkl'):
#       os.remove('user_info_cache.pkl')
#       print("Deleted corrupted cache.")



# This is for if I got booted out of requesting information from MountainProject, so I can remove failed users from the cache and try again. 
climbing_functions.remove_failed_users_from_cache(dry_run=False)

Found 1984 failed entries (request_date is None).
Removed 1984 failed entries from cache. They will be retried on next run.

[201058654,
 200056064,
 201500577,
 105801037,
 109941182,
 200988339,
 200077018,
 201607952,
 200180784,
 200554215,
 112795794,
 201316317,
 200919442,
 200606165,
 201708227,
 200434052,
 107183486,
 201678094,
 201044667,
 108032733,
 200453168,
 201493408,
 110961130,
 200533067,
 112092976,
 110790065,
 200791752,
 200548946,
 105969464,
 201351323,
 201394365,
 200417871,
 200288488,
 201171174,
 200429888,
 110729900,
 201738448,
 200411912,
 200944594,
 200056331,
 201715727,
 112161744,
 200253647,
 201946958,
 200264340,
 108461719,
 201317178,
 112488368,
 201566300,
 201796460,
 7038120,
 110757941,
 200199220,
 201348421,
 201022592,
 200182710,
 109613393,
 108243651,
 108575342,
 107230627,
 201574224,
 201679118,
 201297504,
 201532198,
 201953364,
 200046172,
 107163998,
 202018654,
 201730481,
 201971655,
 201702558,
 201597531,
 200083273,
 200209337,
 201675602,
 200890890,
 200584100,
 200409583,
 200563967,
 7043509,
 201617555,
 200051166,
 200213334,
 201538776,
 202131989,
 201480369,
 107631719,
 200608530,
 200345153,
 202131570,
 201268566,
 201377343,
 200868337,
 107368416,
 200166195,
 200814701,
 111712497,
 112512805,
 200206644,
 11331,
 112433314,
 200196917,
 200197902,
 200266964,
 201395765,
 201283561,
 201554243,
 201710389,
 200982402,
 107085584,
 201425625,
 106153855,
 201110309,
 201369350,
 201825600,
 201433049,
 108322996,
 201402238,
 200745234,
 201344875,
 201816948,
 201811832,
 200474741,
 111635586,
 110459813,
 200440937,
 200296165,
 201448286,
 200836813,
 200634629,
 200473857,
 200149618,
 200061232,
 200224507,
 200415327,
 201554500,
 200632645,
 200943211,
 109130361,
 200177984,
 112797688,
 112413064,
 200249761,
 108974607,
 200354160,
 200938912,
 202075835,
 200437168,
 200436133,
 200418656,
 201159064,
 201838287,
 201241811,
 200847774,
 201479419,
 201496205,
 200287656,
 200811821,
 200148059,
 200891195,
 201312813,
 106189019,
 201708259,
 200615379,
 201671589,
 200208277,
 201704395,
 200109432,
 200347559,
 201393504,
 201076424,
 108344080,
 106945844,
 200323308,
 111322026,
 201960905,
 107888941,
 200415088,
 108267304,
 201851585,
 200197185,
 200683491,
 110719307,
 200882987,
 201505783,
 201751038,
 201364707,
 200247112,
 201254041,
 201740257,
 201083894,
 200330729,
 201923659,
 200635095,
 200431190,
 200467893,
 200053710,
 201879778,
 201760090,
 201989683,
 200216652,
 202046456,
 202004875,
 108391242,
 201512856,
 200286391,
 201301549,
 201806196,
 201831345,
 111790764,
 200374794,
 109506157,
 111711338,
 201990145,
 201420861,
 111542777,
 200920090,
 200688543,
 200090689,
 108280479,
 200355104,
 201764290,
 202011710,
 201162751,
 106350899,
 201537002,
 200968400,
 201270613,
 200219560,
 108283397,
 201248745,
 201294540,
 201297119,
 200706701,
 200120814,
 201608655,
 200373276,
 202398838,
 201922325,
 201274750,
 201796248,
 201311703,
 200231027,
 112278023,
 201217460,
 110395603,
 201272991,
 200177969,
 200441470,
 200661098,
 201782367,
 201500115,
 202149344,
 200778127,
 201272944,
 201478866,
 108168043,
 200102753,
 201286235,
 200578844,
 110088026,
 112080202,
 112391638,
 200451124,
 108933008,
 201374474,
 111226995,
 106503996,
 11156,
 200703148,
 201210984,
 200758821,
 200116481,
 200624036,
 201335528,
 200186714,
 201684948,
 201039461,
 108765079,
 201301691,
 200216863,
 201943681,
 201770646,
 200172230,
 201729571,
 201909124,
 201692797,
 200320869,
 201010835,
 202011699,
 107386475,
 200215667,
 201450858,
 107461253,
 200378314,
 200217557,
 201561037,
 110282915,
 201289052,
 106057045,
 201906717,
 201721981,
 111344588,
 200168871,
 201708245,
 200780939,
 200224843,
 111821708,
 200063614,
 200043229,
 200396738,
 201208756,
 201073005,
 201229207,
 200558222,
 201992652,
 201640086,
 200183491,
 108939344,
 107400563,
 109792012,
 201506420,
 113533186,
 200979104,
 201882906,
 200930949,
 201526649,
 200212497,
 200235812,
 200827125,
 201063363,
 200702939,
 109474377,
 200619017,
 108372237,
 107990106,
 108552057,
 7022560,
 201521308,
 107963088,
 200665765,
 111145765,
 201747184,
 200756102,
 7107211,
 200523816,
 200287340,
 201292468,
 201314210,
 200374605,
 201293607,
 201341569,
 201777654,
 201992649,
 200688912,
 200639052,
 112274042,
 112351073,
 200238425,
 200639367,
 201071918,
 200399404,
 200466692,
 200593525,
 200749199,
 201306365,
 200519542,
 109688349,
 201277026,
 201577991,
 201706733,
 200885732,
 200956286,
 201171649,
 201948091,
 110782098,
 200636531,
 201294888,
 107531215,
 200499614,
 200693505,
 200708205,
 112285440,
 200554961,
 200159460,
 106646308,
 201119757,
 112076658,
 201850554,
 200633956,
 201328864,
 201848247,
 200492460,
 200778873,
 201753187,
 200471241,
 200194423,
 200202373,
 108295473,
 201450223,
 201458274,
 110625470,
 201983118,
 111145244,
 200368278,
 201487089,
 202155990,
 201343627,
 202015731,
 200520324,
 202115444,
 201316652,
 200406793,
 106989427,
 200766126,
 201915750,
 201706891,
 106497287,
 201263804,
 201115779,
 200862223,
 201322918,
 200524616,
 201239654,
 111786150,
 107474229,
 201774583,
 201471363,
 200216714,
 200128336,
 111982068,
 201338321,
 201454629,
 200225026,
 112259711,
 201274315,
 202159795,
 200467625,
 201328388,
 112802432,
 200949116,
 108673806,
 201507519,
 201243476,
 201523390,
 201593453,
 200530521,
 201570889,
 111717609,
 113371873,
 200429713,
 201738167,
 202121132,
 201372706,
 201833911,
 201914348,
 201917369,
 111774874,
 200362060,
 201047849,
 201396750,
 200753107,
 112049871,
 201730891,
 201544304,
 200194908,
 200619573,
 108060742,
 200494918,
 201250571,
 201918465,
 202162327,
 201794472,
 106952502,
 201458864,
 201016326,
 201312382,
 111901710,
 106816785,
 201335952,
 200956898,
 200979171,
 202061005,
 201742197,
 110063034,
 109740385,
 201502289,
 201583513,
 112146327,
 111546336,
 200249421,
 200665140,
 201623838,
 201536324,
 201179377,
 201540954,
 201554511,
 200499139,
 200496897,
 200176100,
 112493324,
 201189335,
 200989854,
 201651443,
 200283003,
 200319558,
 200618465,
 200001907,
 200459186,
 201343527,
 200252102,
 200396944,
 201438285,
 201572783,
 111969430,
 201300784,
 108912672,
 201307916,
 201932947,
 200877402,
 200347494,
 111856972,
 200193693,
 200212138,
 200524778,
 200802408,
 200091943,
 200981973,
 201249752,
 200082972,
 201698806,
 201720774,
 200879817,
 201509069,
 200531182,
 107643102,
 201351089,
 201122011,
 107812430,
 200399641,
 108116183,
 107407406,
 201979448,
 200710719,
 201340244,
 200735089,
 201024239,
 200351908,
 201254599,
 201498654,
 201702169,
 108266997,
 201548981,
 108363423,
 200251584,
 201759233,
 107020260,
 108336698,
 201128256,
 202444251,
 200131583,
 200205302,
 200949831,
 200180044,
 201171113,
 201223688,
 201255864,
 111886577,
 200326440,
 200768958,
 200610730,
 201081819,
 200285891,
 105854023,
 201734235,
 200184246,
 112017596,
 200106560,
 111397499,
 107279803,
 200061717,
 111680703,
 111835329,
 201687310,
 200151906,
 201759038,
 201257420,
 201439191,
 201895670,
 202047471,
 201760739,
 201398303,
 200631359,
 202155916,
 200651362,
 201500100,
 200671842,
 200966574,
 200078133,
 201958048,
 201777038,
 200172183,
 201688176,
 201351626,
 107407794,
 111182841,
 200980975,
 200949744,
 201292677,
 201715079,
 111899416,
 201508552,
 110505874,
 111088046,
 112267259,
 200590671,
 201492444,
 200674162,
 108352656,
 111534913,
 200495599,
 201230671,
 201572722,
 108150892,
 107594696,
 108133875,
 201654502,
 111586559,
 200778226,
 201039215,
 111743042,
 112120122,
 200413224,
 200414485,
 201364853,
 200980716,
 202004669,
 201652118,
 201687239,
 200286955,
 200450484,
 107365302,
 201635789,
 202105672,
 200522361,
 200401534,
 200761293,
 200429711,
 107284917,
 200122244,
 200089760,
 201900970,
 202018953,
 200281057,
 201821971,
 201337863,
 202054618,
 202084226,
 202158432,
 111161113,
 201829220,
 200679291,
 200554726,
 201335931,
 108856439,
 109073050,
 200352558,
 200646656,
 200304955,
 201702280,
 201629832,
 201533518,
 201493359,
 201198884,
 200977875,
 111677486,
 201339960,
 201974738,
 200480738,
 200363149,
 105867714,
 201949408,
 201593405,
 201603263,
 201690388,
 200556749,
 200633979,
 200751176,
 200409678,
 200366716,
 201777950,
 111065591,
 201626563,
 200621002,
 200269142,
 201381730,
 200633258,
 108412707,
 108340305,
 201050429,
 200675475,
 201258149,
 112516727,
 108524782,
 200870493,
 201216006,
 107908012,
 200230613,
 201018893,
 111045596,
 108080137,
 200183812,
 201851452,
 201612061,
 200324684,
 200091123,
 200190507,
 200469690,
 201513457,
 200790267,
 107033190,
 108107173,
 107135028,
 200611666,
 201398484,
 106486749,
 112408821,
 201489290,
 201616469,
 112433428,
 200947752,
 200990159,
 201719715,
 201228248,
 201282071,
 200163862,
 111419049,
 110412401,
 110987088,
 200302931,
 111623347,
 201128844,
 201274235,
 201590304,
 200462236,
 201645979,
 201262586,
 201320293,
 200431967,
 200322441,
 201584880,
 201945156,
 201701520,
 201756869,
 201053866,
 201300293,
 201969991,
 200138734,
 200850708,
 200658134,
 200844150,
 200766791,
 200475572,
 200240211,
 108015653,
 112508423,
 200215013,
 201342847,
 201351043,
 201298911,
 201446559,
 109946183,
 201322155,
 200415213,
 200436756,
 201679399,
 201816330,
 201910348,
 201320021,
 201832818,
 106113630,
 201517786,
 200557499,
 201545194,
 201597534,
 201986138,
 113394075,
 200406021,
 201781125,
 200377351,
 112439437,
 201819389,
 201439581,
 200842929,
 111545688,
 106681644,
 202036998,
 201135769,
 201274416,
 201406324,
 200937338,
 201856353,
 201988957,
 202551660,
 200633340,
 200172922,
 110367517,
 201013517,
 201771688,
 201868564,
 107064066,
 107019871,
 200825968,
 107102879,
 200198879,
 200939249,
 200659057,
 200703372,
 202099527,
 200113603,
 201319576,
 201249058,
 201418112,
 201440164,
 200244771,
 200784098,
 201058516,
 201118062,
 200652762,
 201447965,
 201564505,
 107267482,
 201547514,
 201366051,
 111365246,
 109990756,
 110153966,
 110205782,
 201018827,
 201079695,
 200238325,
 201639203,
 201520853,
 201560269,
 201798545,
 200561680,
 200314358,
 201316008,
 201376515,
 200807900,
 201476136,
 201244364,
 201360532,
 201330279,
 202141649,
 200441372,
 200147699,
 7138296,
 200798430,
 201146485,
 201257483,
 201840140,
 200362679,
 200915443,
 111485061,
 112153204,
 200187201,
 107473909,
 201520517,
 201562853,
 201599212,
 201473788,
 107896813,
 200430545,
 200656761,
 112484424,
 200084721,
 201723534,
 112321066,
 111186559,
 200319401,
 200194862,
 200228652,
 200814930,
 201279583,
 201252138,
 108242295,
 200257718,
 201268115,
 200991139,
 201056464,
 200900720,
 200459314,
 200413163,
 201388497,
 112900598,
 200974059,
 201491863,
 200548129,
 108349367,
 108779375,
 107942229,
 201242773,
 200588002,
 200710427,
 200247776,
 200200829,
 200240021,
 201570482,
 201218876,
 108483120,
 200173801,
 201829326,
 112808318,
 201830511,
 201724143,
 110414589,
 107563467,
 202328472,
 201940594,
 201972600,
 200961041,
 200457566,
 200490195,
 201034825,
 112518935,
 200065821,
 200897087,
 200247104,
 201499832,
 200637660,
 201690072,
 202033377,
 200910663,
 201200040,
 201498287,
 111307669,
 201487003,
 111393782,
 201829509,
 109101198,
 201207719,
 200064872,
 201717117,
 200778403,
 111609918,
 112364679,
 112794921,
 201399216,
 201454433,
 200981409,
 200530822,
 201487019,
 201502582,
 200479256,
 200357655,
 112524057,
 107822139,
 201773936,
 200951240,
 201080647,
 201121554,
 200134563,
 201011550,
 201292828,
 201325009,
 201343355,
 200995134,
 201145225,
 201146808,
 201634855,
 200548318,
 200298278,
 200065753,
 201504643,
 200496887,
 200717132,
 201366144,
 202131464,
 201269581,
 201173685,
 201276196,
 201302957,
 201015838,
 200636441,
 200714404,
 201534042,
 201591489,
 201684259,
 201698985,
 200355092,
 107513398,
 111823672,
 112564276,
 200369194,
 200201110,
 202129710,
 202167254,
 201232027,
 201997515,
 ...]

In [87]:


all_user_dict = climbing_functions.fill_user_dict_with_info(all_user_dict)

Resuming — 2979 users already cached.
JNE: line_list is empty
Skipping user 200239843 (already cached)
Skipping user 108653005 (already cached)
Skipping user 105897447 (already cached)
T D: line_list exists
Orphaned: line_list is empty
Skipping user 106271741 (already cached)
Chase Nelson: line_list exists
Squatting Bear: line_list exists
Alex Fox: line_list exists
Skipping user 200283873 (already cached)
Robert Joyce: line_list exists
Hayley Welch: line_list exists
Evan Weisenberger: line_list exists
Kent Atkinson: line_list exists
Skipping user 107304553 (already cached)
Zachary Lentsch: line_list exists
Skipping user 200421424 (already cached)
richard magill: line_list exists
John Howe: line_list exists
JAtkinson: line_list is empty
Skipping user 107814422 (already cached)
Sean: line_list is empty
Skipping user 107800195 (already cached)
J LO: line_list exists
Evan Martin: line_list exists
Skipping user 112207296 (already cached)
Dan F: line_list exists
Max Grocki: line_list exists
Austin Garcia: line_list is empty
Brice C: line_list is empty
Tanner H: line_list exists
Aidan O'Connor: line_list is empty
TradPrincess Eden: line_list exists
Anonymous User: line_list is empty
Screedy Greebs: line_list is empty
Matteo B: line_list exists
johnh: line_list exists
Skipping user 106440465 (already cached)
Jesse Ryan: line_list exists
Eli B: line_list is empty
Skipping user 108228481 (already cached)
Erik N: line_list exists
Bjorn: line_list exists
Jake Sankari: line_list exists
cstebbins024: line_list exists
文哉 中村: line_list is empty
Jarrid Nakata: line_list is empty
Jason Haas: line_list exists
Skipping user 200711420 (already cached)
Marissa Charlebois: line_list exists
Skipping user 201564537 (already cached)
Tyler Careri: line_list is empty
Ben Web: line_list exists
Skipping user 107417154 (already cached)
Daniel Ballard: line_list is empty
Jason Funk: line_list exists
Lou Hibbard: line_list exists
Samuel G: line_list exists
Skipping user 108344951 (already cached)
Sarah Lacey: line_list exists
Ryan.h153: line_list exists
Gage Juergensen: line_list exists
Daniel Bateman: line_list exists
Logan Arnold: line_list exists
Christopher Mullen: line_list exists
Stephen Schilling: line_list exists
Skipping user 105936209 (already cached)
Petsfed 00: line_list exists
Alex Fyfe: line_list exists
Happy Gilmore: line_list exists
Adam Clatch: line_list exists
Skipping user 110098525 (already cached)
Orphaned User: line_list is empty
Skipping user 108386412 (already cached)
Skipping user 200717675 (already cached)
Maille Gray: line_list exists
Carter Percy: line_list exists
Danny Parker: line_list exists
half-pad-mini-jug: line_list exists
Jeff S: line_list exists
Logan P.: line_list is empty
James McDonald: line_list exists
Skipping user 108363017 (already cached)
Skipping user 107342057 (already cached)
Michael Kesy: line_list is empty
Kevin Shoemaker: line_list exists
Jesse Brown: line_list exists
Athena: line_list exists
Skipping user 112495707 (already cached)
A-W: line_list is empty
Michael Benton: line_list exists
Savannah R: line_list exists
Jack Makin: line_list exists
Ryan Castillo: line_list exists
Tom Ashley: line_list exists
Skipping user 111586693 (already cached)
Dean Patella: line_list is empty
Mary Bjorklund: line_list exists
Scott Coffin: line_list exists
Jonah Koilpillai: line_list is empty
Skipping user 106172145 (already cached)
Iskra: line_list is empty
Ken Sak: line_list is empty
Brian Goeringer: line_list exists
Erik Vance: line_list exists
Skipping user 111232627 (already cached)
Skipping user 200140660 (already cached)
Will West: line_list is empty
Pete F: line_list exists
Brittany Goris: line_list exists
fluff head: line_list is empty
Gabriel Allen: line_list exists
Klimes Walz: line_list is empty
Hodaka Sakurai: line_list exists
Sarah Z: line_list exists
Haley Wintsch: line_list exists
Tommy J: line_list exists
L S: line_list exists
Naveen Pradhan: line_list is empty
Weston S: line_list exists
Lorel Joy: line_list is empty
Skipping user 200619446 (already cached)
EldoFiend: line_list exists
Skipping user 10106 (already cached)
Lucas Emmert: line_list exists
Ryan Doyle: line_list is empty
Mary Gilliland: line_list exists
Nick Orticelle: line_list exists
Mark Kennedy: line_list is empty
Skipping user 200922456 (already cached)
Greg Stark: line_list exists
Skipping user 105846604 (already cached)
Ethan McMahan: line_list exists
Shane Williams: line_list exists
Skipping user 200404978 (already cached)
Connor Mattes: line_list is empty
Joel Pattinson: line_list is empty
Dan Nix: line_list exists
OW Poser: line_list exists
Ryan Henderson: line_list exists
Skipping user 200394444 (already cached)
Skipping user 108939459 (already cached)
Riley Young: line_list is empty
Anonymous: line_list is empty
Kyle Leinen: line_list is empty
Benjamin Foote: line_list is empty
Siobhan: line_list exists
Nicholas Van Epp: line_list exists
Sean _: line_list is empty
Victoria Van Hoose: line_list exists
Eric Warren: line_list exists
Jason Griffin: line_list exists
Nate Spainhoward: line_list exists
Nick Barczak: line_list exists
Pierce J: line_list exists
Jacquie O'Brien: line_list exists
Garrett P.: line_list is empty
Skipping user 111913718 (already cached)
Gabe Birch: line_list exists
Jacob J: line_list is empty
Ian McDonald: line_list exists
Erica Fuchs: line_list exists
James Lambert: line_list is empty
Skipping user 200607819 (already cached)
Anna Volk: line_list exists
Justin Hoich: line_list is empty
Seth Murphy: line_list exists
Patrick Kingsbury: line_list exists
Smash Gamble: line_list is empty
Raysin152: line_list exists
Skipping user 106460214 (already cached)
Benjamin Euresti: line_list exists
Johny A: line_list exists
chris schulte: line_list is empty
Reuben Eliason: line_list exists
DWF 3: line_list exists
IDK what I am doing: line_list exists
Ryan Strother: line_list exists
Davin Bagdonas: line_list is empty
Tyler Smeenk: line_list exists
helk0003: line_list is empty
Yoni Argov: line_list is empty
Skipping user 200142413 (already cached)
Ryan Dresser: line_list exists
Stellar's John: line_list exists
Patrick B: line_list is empty
Skipping user 112938047 (already cached)
Jack Barr: line_list is empty
Jamie G-Child: line_list exists
WeBeJammon: line_list is empty
Alex Fischer: line_list exists
Skipping user 108411681 (already cached)
Jieyi Zhou: line_list exists
JJ C: line_list exists
Cameron Cutting: line_list exists
Jimmy hoctor: line_list exists
Tyler McKenzie: line_list is empty
Alec Backhus: line_list exists
Hankus Pankus: line_list is empty
Skipping user 200680933 (already cached)
Andreas DeGraeve: line_list exists
Stan Darsh: line_list exists
Evan C: line_list exists
Erik Svedberg: line_list exists
Michael Alessi: line_list exists
Ben Peterson 2: line_list exists
Alex Z: line_list is empty
Austin L: line_list exists
Skipping user 109212068 (already cached)
Pike Somlyay: line_list exists
Jackson J: line_list is empty
Daniel Havlat: line_list exists
Skipping user 201176880 (already cached)
Skipping user 201126161 (already cached)
Skipping user 107521255 (already cached)
Connor FM: line_list exists
Ryan Becwar: line_list exists
Kai Burkhardt: line_list exists
Spider monkey: line_list is empty
Skipping user 111850671 (already cached)
Cole Hennies: line_list exists
Skipping user 107328886 (already cached)
Shane Garland: line_list is empty
Shawn Green: line_list is empty
Spencer Anderson: line_list exists
Riley Cooper: line_list is empty
Matt Heininger: line_list is empty
Michael E.: line_list exists
Skipping user 108046773 (already cached)
Sam MacIlwaine: line_list exists
Matthew Licina: line_list exists
Logan Barnes: line_list is empty
Choss Pirate: line_list exists
Ari JS: line_list exists
Eytan Libedinsky: line_list exists
Grey Rat: line_list exists
Rowe Wilson-Scott: line_list exists
Ol Jellylegs: line_list is empty
J.LemmonPie: line_list is empty
Sam Zavislan: line_list exists
Gus Meyers: line_list exists
Miller Andrews: line_list exists
Alex Leslie: line_list exists
Skipping user 107201154 (already cached)
Alice Bennett: line_list exists
Skipping user 112116113 (already cached)
Pat Brehm: line_list is empty
Skipping user 200591060 (already cached)
I D: line_list exists
Clay Stoner: line_list exists
Skipping user 107995117 (already cached)
Cass Ann: line_list exists
Skipping user 107996606 (already cached)
Ethan P: line_list exists
Josh Harrison: line_list is empty
Skipping user 200280347 (already cached)
Skipping user 111771784 (already cached)
Luke McKee: line_list exists
Zach Blahnik: line_list is empty
Gareth Ellis: line_list is empty
Bill Kinter: line_list exists
Ben M: line_list exists
Sean Dunlop: line_list exists
Avery C: line_list is empty
Blake Greener: line_list exists
Skipping user 109306319 (already cached)
Troy Tetreault: line_list exists
Zach Tulgetske: line_list is empty
Trevor Goselin: line_list is empty
Jay Schenk: line_list exists
Will S: line_list exists
John Davis: line_list exists
Charlie Malone: line_list is empty
eric whewell: line_list exists
Rob Fulton: line_list exists
Blake B: line_list exists
Jack Cerullo: line_list is empty
Jackson Engstrom: line_list exists
Skipping user 200423818 (already cached)
Miles Johnson: line_list exists
Chris OHara: line_list exists
Nathan Williams: line_list exists
Dana F: line_list is empty
Meredith G: line_list is empty
James Horne: line_list exists
Soy Park: line_list exists
Kristin Rector: line_list is empty
Scott Page: line_list is empty
Lydia Davidson: line_list is empty
Brandon Doherty: line_list is empty
MonteGraham Graham: line_list exists
Orange Crush: line_list exists
Bryce Kerscher: line_list exists
Sean Wolf: line_list exists
Skipping user 12525 (already cached)
Skipping user 109152722 (already cached)
Skipping user 108085357 (already cached)
Dave Hug: line_list exists
Forrest Cole: line_list is empty
sendit: line_list is empty
Joshua Harrington: line_list exists
Kurtis Anderson: line_list exists
David Germer: line_list is empty
Skipping user 105822848 (already cached)
Matt Kuehl: line_list exists
Sam Coffin: line_list exists
David Aguasca!: line_list exists
Skipping user 105821890 (already cached)
Liz H: line_list is empty
e: line_list is empty
Andrew Ziebarth: line_list exists
J Rees: line_list exists
adamgable: line_list exists
Lauren Hansen: line_list is empty
Maya Greene: line_list is empty
Brian Kreinbrink: line_list exists
Alex Commisso: line_list exists
Jess Kostka: line_list exists
Carlos Garcia: line_list exists
Skipping user 200735334 (already cached)
J W: line_list is empty
Mia Hill: line_list is empty
ADAM ANDREWS: line_list exists
Noah Ledat: line_list is empty
Jay Beans: line_list exists
Ben Krege: line_list exists
Xavier Merino: line_list is empty
Jared Friedman: line_list is empty
Grant King: line_list is empty
Skipping user 200420085 (already cached)
Skipping user 200463855 (already cached)
Skipping user 200485683 (already cached)
Peter Stratford: line_list is empty
Andy Parzynski: line_list is empty
Skipping user 200593080 (already cached)
Skipping user 200630734 (already cached)
Jackson Birrell: line_list is empty
Skipping user 200042168 (already cached)
Tom Cairns: line_list is empty
Skipping user 200173852 (already cached)
Sophia Espa: line_list is empty
Steven Keiser: line_list is empty
Skipping user 108317032 (already cached)
Skipping user 109707618 (already cached)
Skipping user 111273796 (already cached)
Will Kirby: line_list is empty
Mackenzie Bell: line_list is empty
Skipping user 112391726 (already cached)
J Fell: line_list is empty
Skipping user 106047496 (already cached)
Skipping user 106201630 (already cached)
Skipping user 106709875 (already cached)
Skipping user 106920443 (already cached)
Skipping user 108200547 (already cached)
Jack Leever: line_list exists
Thomas Zenner: line_list exists
TJ Bindseil: line_list exists
Elizabeth Butler: line_list exists
Skipping user 109761068 (already cached)
Kris Schrijvers: line_list is empty
Sasha Shokhrin: line_list is empty
Amanda Clementel: line_list is empty
Nick Ross: line_list exists
Skipping user 111871501 (already cached)
Skipping user 107227104 (already cached)
Jake Chase: line_list is empty
Weston Kennedy: line_list is empty
Hunter Iannozzi: line_list exists
Jonas Helton: line_list exists
Connor White: line_list exists
Ryan Westerguard: line_list exists
Skipping user 105946523 (already cached)
Matt S Smith: line_list exists
Nathan McDonald: line_list is empty
Corrye Fulton: line_list is empty
Kevin Landolt: line_list exists
Skipping user 111963269 (already cached)
Kevin Heinrich: line_list exists
Shwooplkock: line_list is empty
Skipping user 105998198 (already cached)
Hunter Warren: line_list is empty
Skipping user 200360188 (already cached)
Max F: line_list exists
Martin S: line_list exists
villlein: line_list exists
Dusty: line_list exists
Preston Pettigrew: line_list exists
Michelle Schol: line_list exists
Nick G: line_list exists
Lucille Glassman: line_list exists
Skipping user 200684836 (already cached)
Elizabeth Cupp: line_list is empty
Alejandro L: line_list exists
Skipping user 109040845 (already cached)
Kavee Kirschner: line_list is empty
sljazz19: line_list is empty
Tenaya B: line_list exists
Matthew Stefanko: line_list is empty
Matt Orlando: line_list exists
niche pome: line_list exists
Andy Thorsell: line_list exists
Skipping user 200083634 (already cached)
Mitchell Casazza: line_list is empty
Josh Coppinger: line_list exists
Andy Librande: line_list exists
ANGUS WIESSNER: line_list exists
eric1234: line_list exists
Marcos M: line_list exists
Matt Gibson: line_list exists
Austin Lowe: line_list exists
Noah Bergman: line_list exists
Tristan Smith: line_list exists
Jack Rosky: line_list is empty
M D: line_list exists
Skipping user 200584942 (already cached)
Jeremy C: line_list exists
Skipping user 107896521 (already cached)
Matt Ritter: line_list exists
Christian Payant: line_list exists
Brandon Kutrovacz: line_list exists
Cody Brown: line_list exists
Mark Younkins: line_list exists
Sam Ridley: line_list exists
Michele Zerbe: line_list exists
Jeff M: line_list exists
Mitch Friedeman: line_list exists
Anus Herder: line_list exists
Skipping user 109744782 (already cached)
Skipping user 109638995 (already cached)
David Cobb: line_list is empty
Ian Moffatt: line_list exists
Lauren Hatfield: line_list exists
NPlasterer Plasterer: line_list exists
dylanstowers: line_list is empty
Riley Kelehan: line_list exists
Adam Gallimore: line_list exists
Grant B: line_list is empty
Skipping user 200078818 (already cached)
Camlan Smith: line_list is empty
Lane Alexander: line_list exists
Evan Parker: line_list is empty
Mateo Grasso: line_list is empty
Jeff Blockwick: line_list exists
Jackson Carpenter: line_list is empty
Danny Baker: line_list is empty
Skipping user 108043082 (already cached)
Tom Jones: line_list exists
nmesen: line_list exists
Jack Curran: line_list exists
Bekah Itz: line_list is empty
Captain Derp: line_list exists
Wes O'Rourke: line_list exists
Ryan Hrbek: line_list is empty
James Swift: line_list is empty
Tyler Mossor: line_list exists
Casey Hale: line_list exists
Kyra Schmidt: line_list exists
Ryan Eastman: line_list exists
Shane Davis: line_list exists
Skipping user 110053057 (already cached)
Jake R: line_list exists
Matt B: line_list exists
Nick Ibarluzea: line_list exists
Dennis Frank: line_list exists
Skipping user 105950084 (already cached)
Oliver Wermus: line_list is empty
Garrett Herrick: line_list is empty
Jon Frisby: line_list exists
Skipping user 200445754 (already cached)
Skipping user 200256148 (already cached)
Luke G: line_list exists
Kenzi Stemp: line_list exists
Emily Bero: line_list is empty
Emily Gross: line_list is empty
Mark Young: line_list exists
Melissa Kline: line_list exists
Skipping user 200218720 (already cached)
Will Fritzke: line_list exists
Andy Hansen: line_list exists
SAL: line_list exists
Jacob Aid: line_list is empty
Ryan Oh: line_list is empty
Skipping user 200621659 (already cached)
Chris Arnold: line_list exists
BeccaSaurusWrecks: line_list is empty
Skipping user 108166735 (already cached)
Kevin Karn: line_list exists
Skipping user 200050311 (already cached)
Skipping user 108684526 (already cached)
Skipping user 107923457 (already cached)
Tobias Koch: line_list exists
Andy K: line_list is empty
Skipping user 200552300 (already cached)
Skipping user 200668718 (already cached)
Ahn G: line_list exists
Graham Sudweeks: line_list exists
D Scott Clark: line_list exists
monkeyvanya: line_list exists
Skipping user 201076046 (already cached)
Skipping user 201277624 (already cached)
Skipping user 112053262 (already cached)
Skipping user 200291765 (already cached)
Hope Wentzel: line_list exists
Kass Brexel: line_list is empty
Jay Knower: line_list exists
Brian Weinstein: line_list is empty
slim: line_list exists
Josh K: line_list is empty
ALuckyDuck: line_list exists
Stephanie Houghton: line_list exists
Jake Albright: line_list exists
Molly Mulcahy: line_list exists
Rob Mudie: line_list is empty
Cory N: line_list exists
Michael S: line_list exists
Lily Jones: line_list is empty
Eric Lippert: line_list is empty
Wyatt Murphy: line_list is empty
remy goc: line_list is empty
Michael Kaleita: line_list is empty
Wyatt Murphy: line_list is empty
David Thien: line_list is empty
Gus Kristiansen: line_list is empty
Rachel Zuckerman: line_list is empty
Skipping user 200854678 (already cached)
Skipping user 200897949 (already cached)
Skipping user 200937678 (already cached)
Jack Dodson: line_list is empty
Reese Irwin: line_list exists
Skipping user 105814027 (already cached)
Brant Whitaker: line_list exists
Maddy Stone: line_list exists
Andrew Mularoni: line_list exists
Shea Allen: line_list is empty
Daniel Feldman: line_list exists
Skipping user 200492380 (already cached)
Nick Patilsen: line_list exists
matthewphoto Williams: line_list is empty
Dustin Roth: line_list exists
Mitch alons: line_list exists
Skipping user 108319693 (already cached)
Skipping user 106224851 (already cached)
Brandon Jones: line_list is empty
Lucas Roberge: line_list is empty
Nick Gaston: line_list exists
blaine: line_list exists
Anonymous: line_list is empty
Consuelo Redhorse: line_list exists
Julius Mazer: line_list exists
Kent Rush: line_list exists
Mitch Findley: line_list is empty
Tucker Kern: line_list is empty
Morgan Janovec: line_list is empty
Caden Larson: line_list is empty
Wayne Monnett: line_list exists
Lincoln Craven-Brightman: line_list exists
KateC Thayer-Calder: line_list exists
Kyle Moncrieff: line_list is empty
D Graham: line_list exists
Zac Sparrow: line_list is empty
Devin Scheid: line_list exists
Evan Stoecker: line_list is empty
Skipping user 108918151 (already cached)
Zoey Nelson: line_list exists
Skipping user 200381859 (already cached)
Skipping user 107073729 (already cached)
Skipping user 107741581 (already cached)
Skipping user 109924181 (already cached)
Jessie CL: line_list exists
Skipping user 110859480 (already cached)
Alec Manougian: line_list exists
Skipping user 112212516 (already cached)
Oak Nelson: line_list exists
Anonymous: line_list is empty
Skipping user 107702638 (already cached)
Clark S: line_list is empty
Eddie Garza: line_list exists
Aspen Smith: line_list exists
Tara D: line_list is empty
David A: line_list exists
Josh Cox: line_list exists
misha s: line_list is empty
Skipping user 107848134 (already cached)
JD Borgeson: line_list exists
nick j taylor: line_list exists
Dylan Cross: line_list exists
Skipping user 112105385 (already cached)
Stuart Lewis: line_list is empty
Devin Bidstrup: line_list exists
Sam Benedict: line_list exists
Tombo: line_list exists
tim: line_list exists
Tom Rangitsch: line_list exists
Aerili: line_list exists
Anonymous Climber: line_list is empty
Jarrett Widman: line_list is empty
Tyler: line_list is empty
Skipping user 107407378 (already cached)
Justin Rajewski: line_list exists
Braxton Francom: line_list exists
Wade Griffith: line_list exists

In [88]:
user_info_df

,user_ID,user_name,user_URL,request_date,location,age_at_request_date,listed_gender,guessed_gender
0,108295877,Jason Akua Makana Petty,https://www.mountainproject.com/user/108295877...,2026.0,"Phoenix, AZ",NaN,None,male
1,106662570,Andy L,https://www.mountainproject.com/user/106662570...,2026.0,None,NaN,Male,male
2,111204599,Troy Fauteux,https://www.mountainproject.com/user/111204599...,2026.0,"Henniker, NH",31.0,Male,male
3,105941791,AWinters,https://www.mountainproject.com/user/105941791...,2026.0,None,NaN,Male,unknown
4,109293842,Brendan Cathcart,https://www.mountainproject.com/user/109293842...,2026.0,"Bishop, CA",NaN,None,male
...,...,...,...,...,...,...,...,...
4958,201557309,Jenevieve B,https://www.mountainproject.com/user/201557309...,NaN,None,NaN,None,unknown
4959,111487392,Shayna H,https://www.mountainproject.com/user/111487392...,2026.0,"San Diego, CA",NaN,Female,female
4960,200418847,Mason Chin,https://www.mountainproject.com/user/200418847...,2026.0,"San Francisco, CA",NaN,Male,male
4961,200703432,Liam Heyman,https://www.mountainproject.com/user/200703432...,2026.0,"Oakland, CA",NaN,Male,male
4962,200794958,Jade Ferragut,https://www.mountainproject.com/user/200794958...,2026.0,None,25.0,Female,female

In [89]:
user_info_df = pd.DataFrame(all_user_dict.values())

# if the information request fails for some users, their gender will not be guessed so this needs to be pulled separately. 
user_info_df = climbing_functions.fill_missing_guessed_gender(user_info_df)

print(user_info_df.shape)
user_info_df.head()

Filled guessed_gender for 0 rows.
(1110, 8)

,user_ID,user_name,user_URL,request_date,location,age_at_request_date,listed_gender,guessed_gender
0,105813840,JNE,https://www.mountainproject.com/user/105813840...,NaN,None,NaN,None,unknown
1,200239843,Bailey Moore,https://www.mountainproject.com/user/200239843...,2026.0,Yosemite,NaN,Male,mostly_female
2,108653005,bart cubrich 1,https://www.mountainproject.com/user/108653005...,2026.0,"Laramie, WY",NaN,None,male
3,105897447,Michael Molony,https://www.mountainproject.com/user/105897447...,2026.0,Chattanooga,NaN,Male,male
4,108678435,T D,https://www.mountainproject.com/user/108678435...,2026.0,Splatte,33.0,Male,unknown

In [90]:
user_info_df.to_csv(f"data/{datetime.now().strftime('%Y%m%d_%H%M%S')}_{AREA_NAME}_user_info_df.csv", index=False)

In [91]:
area_df = area_df.merge(
    user_info_df[['user_ID', 'user_URL', 'location', 'age_at_request_date', 'listed_gender', 'guessed_gender']],
    left_on='user.id',
    right_on='user_ID',
    how='left'
).drop(columns='user_ID')

area_df.head()

,Route,Location,URL,Avg Stars,Your Stars,Route Type,Rating,Pitches,Length,Area Latitude,...,leadStyle,pitches,tick_createdAt,tick_updatedAt,rockRating,user_URL,location,age_at_request_date,listed_gender,guessed_gender
0,Joy Ride,Campjack Rocks > Vedauwoo > Laramie Area > Wyo...,https://www.mountainproject.com/route/10687111...,2.0,-1,Boulder,V0-1,1,NaN,41.20228,...,,1.0,2010-08-26T00:00:00.000000Z,2010-08-26T00:00:00.000000Z,NaN,https://www.mountainproject.com/user/106856483...,Wyoming,NaN,Male,unknown
1,Sweet Sweet Lovin',Campjack Rocks > Vedauwoo > Laramie Area > Wyo...,https://www.mountainproject.com/route/10576419...,2.8,-1,Boulder,V1,1,10.0,41.20228,...,NaN,NaN,NaN,NaN,NaN,https://www.mountainproject.com/user/10382/ric...,oregon climber,NaN,None,male
2,Sweet Sweet Lovin',Campjack Rocks > Vedauwoo > Laramie Area > Wyo...,https://www.mountainproject.com/route/10576419...,2.8,-1,Boulder,V1,1,10.0,41.20228,...,,1.0,2006-02-16T00:00:00.000000Z,2006-02-16T00:00:00.000000Z,NaN,https://www.mountainproject.com/user/105787473...,"Laramie, WY",41.0,Male,unknown
3,Sweet Sweet Lovin',Campjack Rocks > Vedauwoo > Laramie Area > Wyo...,https://www.mountainproject.com/route/10576419...,2.8,-1,Boulder,V1,1,10.0,41.20228,...,,1.0,2008-06-30T00:00:00.000000Z,2008-06-30T00:00:00.000000Z,NaN,https://www.mountainproject.com/user/105844582...,"Bend, OR",NaN,Male,mostly_female
4,Sweet Sweet Lovin',Campjack Rocks > Vedauwoo > Laramie Area > Wyo...,https://www.mountainproject.com/route/10576419...,2.8,-1,Boulder,V1,1,10.0,41.20228,...,NaN,NaN,NaN,NaN,NaN,https://www.mountainproject.com/user/105881068...,Wyo,NaN,Male,unknown

In [92]:
area_df['likely_gender'] = area_df.apply(climbing_functions.assign_likely_gender, axis=1)

In [93]:
area_df.to_csv(f"data/{datetime.now().strftime('%Y%m%d_%H%M%S')}_{AREA_NAME}_area_df_with_user_info.csv", index=False)

In [94]:
# if the information request fails for some users, their gender will not be guessed so this needs to be pulled separately. 

user_info_df = climbing_functions.fill_missing_guessed_gender(user_info_df)

Filled guessed_gender for 0 rows.